### ISSUE TITLE
Add bit-packed serialization mechanism

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-python#10]
currently the `Serializable` interface supports `to_json` and `from_json`

as a consuming application i would like to serialize and deserialize using a binary serialization mechanism so that i can conserve space for objects in transit and on disk.

both `message pack` and `protobuf` are reasonable options.

Additionally, as a consuming application i would like to have strong confidence that the serialization parsers behave consistently so i do not have to worry about malformed data issues.

consider using [EverParse](https://www.microsoft.com/en-us/research/publication/everparse/)

**Comment by keithrfung** [comment]
This is going to be pulled into the higher level and not into the base repository.
