### ISSUE TITLE
pypi / pip metadata is missing

### ISSUE THREAD

**Issue by danwallach** [microsoft/electionguard-python#105]
First, congrats on hitting the big "1.0.0" release. Now that you're on pypi.org, you don't have a project description.

https://pypi.org/project/electionguard/

It does correctly link to the homepage and such, but you want a local description there as well.

**Comment by keithrfung** [comment]
We're aware. That is being manually edited to allow a bit of formatting.

**Comment by keithrfung** [comment]
Since we already have a card for this, I'll add the details here:

- [ ] Add `long_description`
- [ ] Add `long_description_content_type`
- [ ] Remove "ChangeLog" from Project Urls
- [ ] Add "GitHub Documentation" to Project Urls
- [ ] Add "ReadTheDocs" to Project Urls

```py
from setuptools import setup

# read the contents of your README file
from os import path
this_directory = path.abspath(path.dirname(__file__))
with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    long_description = f.read()

setup(
    name='an_example_package',
    # other arguments omitted
    long_description=long_description,
    long_description_content_type='text/markdown'
)
```
