### ISSUE TITLE
Reorganize tests folder and adjust `make` commands

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#109]
**Underlying concern**
Windows currently bypasses parts of the tests because the property testing with hypothesis exceeds the time limits on the builds. This is particular just to how windows handles the virtual environments and is not indicative of other parts of the unit tests which pass. The property tests need to be isolated so they can still be run on Linux and MacOS.

- [ ] **Update Make Commands**
* Only property tests : `make property-tests`
* Only integrations tests: `make integration-tests`
* Only unit tests: `make unit-tests`
* All tests: `make test`
* Coverage for all tests: `make coverage`

- [ ] **Update Folder**
📂  tests
---- 📂  integration
---- 📂  property
---- 📂  unit

- [ ] **Update Continuous Integration**

**Comment by danwallach** [comment]
If we had test parameters (https://github.com/microsoft/electionguard-python/issues/76), this would fix the problem.

**Comment by TuTomasz** [comment]
Would like to help out with this one also made some progress locally.
