### ISSUE TITLE
provide virtual machine

### ISSUE THREAD

**Issue by MellowVoidUser** [microsoft/electionguard-python#124]
While I'm happy with the latest option of the pypi package I think it would be an enhancement if you could add a virtual machine image. Something along the lines nextcloud does it on https://github.com/nextcloud/vm . This would make it easier/faster for non-techies to get involved, start experimenting and providing feedback.

**Comment by rc-ms** [comment]
Hello there,

Thank you for the suggestion.  We fully intend to make the learning curve for working with ElectionGuard easier for non-tech folks.  While making a virtual machine image for this library is unlikely, we fully intend to make buildable examples of use cases with our reference implementation releases (such as our [ballot marking device](https://github.com/microsoft/electionguard-ballot-marking-device)).

Thanks again for your interest
