### ISSUE TITLE
discrete_log initialization doesn't work if there isn't an "event loop"

### ISSUE THREAD

**Issue by danwallach** [microsoft/electionguard-python#130]
I'm working on getting EG to work with `ray.io`, a cluster computing framework. I ran into one issue with `async` code in `dlog.py`. The gist of it is that the call to initialize `__dlog_lock` was failing, and I was getting an error about a missing "event loop". Turns out, the way Ray was running the code was tickling this issue.

The solution is really straightforward: delay initialization of the lock variable until you're inside `__discrete_log_internal`.

**Comment by keithrfung** [comment]
No need to mention a PR is incoming. Simply assign yourself to the issue.
