### ISSUE TITLE
Chaum-Pedersen logic needs to be modular, support decryption proofs

### ISSUE THREAD

**Issue by danwallach** [microsoft/electionguard-python#149]
Right now, we have three different kinds of Chaum-Pedersen proofs: "constant", "disjunctive", and a third one that's roughly the same as the "constant". None of these support decryption proofs, where you prove that you decrypted using the secret key, and you don't know the encryption nonce. This would require a fourth variant on Chaum-Pedersen. That's too much.

Proposed solution: create a "generic" Chaum-Pedersen procedure, which just proves that for two tuples (g, g^x), (h, h^x), they share the same x, without revealing x. This "generic" Chaum-Pedersen procedure becomes a reusable component to prove that you know the nonce, or to prove that you know the decryption key, or to construct something more complicated like a disjunctive proof (where one constant is valid and the other is fake, but you're only committing to the sum of them).

**Comment by keithrfung** [comment]
Closing this for now, may be reopened later or opened as smaller tickets.
