### ISSUE TITLE
ProofUsage not serialized in a useful way

### ISSUE THREAD

**Issue by danwallach** [microsoft/electionguard-python#151]
Right now, the "name" of a proof is derived from its class name, which is fine, but the "usage" of a proof is currently serialized as the value of the ProofUsage enum ("SecretValue", "SelectionLimit", etc.). This is less than meaningful to somebody reading these proofs as JSON trying to figure out what's going on.

The obvious alternative is to instead write out the enum's value ("Prove knowledge of secret value", "Prove value within selection's limit, etc.). This doesn't necessarily deserialize usefully, but that can be ignored since we "know" what sort of proof we're trying to read in any given circumstance. Or, perhaps we could write out both the key and value.

**Comment by keithrfung** [comment]
This was done intentionally. When discussed the preference was just to have the output and maintain the enumeration text in code exclusively.
