### ISSUE TITLE
Allow Selection ID to reoccur within a ballot

### ISSUE THREAD

**Issue by rkorsak** [microsoft/electionguard-python#168]
There are at least two places within the code that assume the ID of a selection is unique _within the entire ballot_.  We should instead only assume that selection IDs are unique within a given contest.

- [`get_spoiled_shares_for_selection`](https://github.com/microsoft/electionguard-python/blob/cf995e935304f0b97e6e8fd8bb8adf8465b5c2e0/src/electionguard/decryption_share.py#L382-L391) accepts the ID of a ballot and a selection, and finds all shares for that selection.  We should require the contest ID as well.
- [`reconstruct_decryption_contests`](https://github.com/microsoft/electionguard-python/blob/cf995e935304f0b97e6e8fd8bb8adf8465b5c2e0/src/electionguard/decryption.py#L483-L491) also makes this assumption in its loop.

There may be more areas of the code similar to the above - we need to update the tests to include a shared selection ID across contests and flush out any others.

**Comment by byusti** [comment]
Hi, I would like to pick up this issue
