### ISSUE TITLE
🐛 Parties is hashed twice in the Election Description

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#178]
On this line
https://github.com/microsoft/electionguard-python/blob/main/src/electionguard/election.py#L576

parties is hashed twice into the election description when it only needs to be hashed once.

**Comment by rkorsak** [comment]
If fixed, would this invalidate all existing election description hashes?

**Comment by iadi7ya** [comment]
Hey @keithrfung , I would like to fix this. Can you please assign this to me.
