### ISSUE TITLE
Escape Ascii Characters for Serialization and Regenerate Sample Data

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#179]
The `jsons` library depends on `json`. One feature that we're not using is the `ensure_ascii=False`. This keeps the output in `unicode` not in `\uXXXX` sequences. 

Json documentation: https://docs.python.org/2/library/json.html#basic-usage
Jsons documentation https://github.com/ramonhagenaars/jsons/blob/aa565f530b3e72c5854cf11b10b1d90daa85f047/jsons/_dump_impl.py#L71

This is relevant for `electionguard.serializable` anywhere that `dump` or `dumps` from `jsons` is used. 

Add this property in and ensure use `make generate-sample-data` to regenerate the 5 ballot threshold and non threshold sets.

**Comment by iadi7ya** [comment]
Hi @keithrfung I would like to work on this. It would be great if you could assign this to me.

**Comment by iadi7ya** [comment]
Hi @keithrfung I have changed the code. Also make generate-sample-data is executed successfully. Please review the PR.
