### ISSUE TITLE
✨ Create separate DTO models

### ISSUE THREAD

**Issue by rkorsak** [microsoft/electionguard-python#180]
Given our serialization woes, we've been discussing the possibility of creating something like `electionguard_models` as a separate python package, particularly for use by anyone writing a python server or client over ElectionGuard.  It would contain Pydantic-friendly DTOs to represent the core EG models, with any sensible validation restrictions and clear descriptions built in.  Each model should also be paired with functions to map to/from core EG models.

**Comment by gagandeepp** [comment]
interested please assign @keithrfung

**Comment by keithrfung** [comment]
Going to close this for now @rkorsak. This piece if hard to complete currently with the implementation of `BaseElement` and the math library. This can be revisited as a concept later. Especially since some of the serialization was recently changed.
