### ISSUE TITLE
🐛 Election dates should be hashed with ticks

### ISSUE THREAD

**Issue by rkorsak** [microsoft/electionguard-python#186]
We're [using `isoformat()` to produce a hash-able representation of the start and end datetimes](https://github.com/microsoft/electionguard-python/blob/e5c66332dedf116e5f905dcb84648ceef83a61f4/src/electionguard/election.py#L570) for each ElectionDescription.  Unfortunately, [the behavior of `isoformat` differs](https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat) depending on whether a timezone is present, which causes the same datetime to hash differently depending on whether it's produced with or without a UTC timezone.  

Because the same instant in time should hash to the same value regardless of its serialization format, we should be using ticks to produce the hash instead.  It's probably a good idea to fix #178 while we're in here.

**Important**: this will invalidate existing election hashes!  We will need to re-generate any serialized samples.

**Comment by devil-cyber** [comment]
Can i work on this

**Comment by rkorsak** [comment]
Thanks for volunteering to jump on this, @devil-cyber!  I actually have a solution for this one in progress (we accidentally tagged it for Hacktoberfest).  Please do take a look at any other `hacktoberfest` labeled issues to grab, though!

**Comment by devil-cyber** [comment]
Ok no problem
