### ISSUE TITLE
✨ Deserialize ISO-8601 dates with `Z`

### ISSUE THREAD

**Issue by rkorsak** [microsoft/electionguard-python#187]
We're using `isoformat` and `fromisoformat` to serialize/deserialize datetimes, [which unfortunately doesn't handle the `Z` formatting for UTC](https://stackoverflow.com/questions/19654578/python-utc-datetime-objects-iso-format-doesnt-include-z-zulu-or-zero-offset).

When deserializing datetimes, we would like **both** offsets (e.g. `-05:00`) and `Z` to be supported.

**Comment by jacobggman** [comment]
can I do that?

**Comment by rkorsak** [comment]
Hi @jacobggman, thanks for the interest in this!  Normally this would be a great hacktoberfest issue, but we have a solution in progress (this one and #186 were accidentally labeled for Hacktoberfest).  Please do take a look at any other `hacktoberfest` labeled issues to grab, though!
