### ISSUE TITLE
test_decryption_mediator absurdly slow

### ISSUE THREAD

**Issue by ddrm86** [microsoft/electionguard-python#220]
I am trying to build the project using `make` and everything works fine... until it starts running the tests and reaches _test_decryption_mediator.py_, which takes forever. I tried several times and left it running for several hours until I got tired. I know it is working because the green dots keep appearing, but it is using almost no CPU at all. The whole output of `make` is available [here](https://www.dropbox.com/s/btrhbj3hl1s1e1w/election_guard_make_output.txt?dl=0).

System specs:

- Ubuntu 19.10
- RAM: 15,6 GiB
- CPU: Intel i5-4670K @ 3.40GHz x 4
- GPU: GeForce GTK 770

**Comment by ddrm86** [comment]
Update: This test runs reasonably quick in Windows 10, and the task manager shows the process is using about 30% of the CPU, while in Ubuntu 19.10 the CPU use is negligible.

On the other hand, in Windows 10 three tests from `test_decrypt_with_secrets.py` fail -> FF.F...

**Comment by ddrm86** [comment]
Update 2: It works fine in a clean installation of Ubuntu 20.04, using 100% of the CPU.

**Comment by AddressXception** [comment]
This is interesting.  I have seen this run very slow on Mac at times in the past as well. One thing of note is that hypothesis can consume a ton of resources in the `Shrink` phase if it finds an exception case.  maybe that is happening here.  We typically disable the shrink phases in preference for simply letting the test fail, but it's possible this was missed somewhere.

perhaps we should benchmark this process and see which processes are running slowly.
