### ISSUE TITLE
Publish incorrectly computes the directory in project directory instead of passed in directory

### ISSUE THREAD

**Issue by jpic** [microsoft/electionguard-python#258]
In [publish.py](https://github.com/microsoft/electionguard-python/blob/main/src/electionguard/publish.py), all DEVICES_DIR etc are computed at module evalution time which causes DEVICES_DIR in publish to be "results/devices" even when passing a results_directory different from the default: "results".

I've [hacked cwd in our open source multitenant electionguard platform](https://gitlab.com/electisNGO/electeez/-/blob/master/djelectionguard/views.py#L229-254), but fixing results_directory would be nice, I'd like to make a PR if you don't mind.

**Comment by jpic** [comment]
In case anybody has the same problem, here's the workaround that works for us:

```python

            path = os.path.join(settings.MEDIA_ROOT, f'contest-{self.instance.pk}')
            if not os.path.exists(path):
                os.makedirs(path)
            cwd = os.getcwd()
            os.chdir(path)

            from electionguard.publish import publish
            from electionguard.election import ElectionConstants
            publish(
                self.instance.description,
                self.instance.context,
                ElectionConstants(),
                [self.instance.device],
                self.instance.store.all(),
                self.instance.ciphertext_tally.spoiled_ballots.values(),
                publish_ciphertext_tally(self.instance.ciphertext_tally),
                self.instance.plaintext_tally,
                self.instance.coefficient_validation_sets,
            )
            os.chdir(settings.MEDIA_ROOT)
            shutil.make_archive(
                f'contest-{self.instance.pk}',
                'zip',
                f'contest-{self.instance.pk}',
            )
            os.chdir(cwd)
```

**Comment by keithrfung** [comment]
We're looking at revisiting serialization as a whole. This function was always kind of meant as a helpful piece to ensure you grabbed all the result data. Let's rename this issue and you can try to adjust the paths against this issue.
