### ISSUE TITLE
Necessity of contest_has_valid_number_elected and contest_has_valid_votes_allowed ?

### ISSUE THREAD

**Issue by jpic** [microsoft/electionguard-python#259]
I was asked to setup an election where number_elected=5 and votes_allowed=3, but it [won't validate](https://github.com/microsoft/electionguard-python/blob/main/src/electionguard/election.py#L379)

I tried to force `contest_has_valid_number_elected = True` and `contest_has_valid_votes_allowed = True` in there and the whole process still ran smoothly.

In my implementation I will force number_elected=1 which means that there will be a mistake in the generated manifest.json that voters will be downloading.

Any objections to removing contest_has_valid_number_elected and contest_has_valid_votes_allowed to support a wider range of use cases ?

**Comment by AddressXception** [comment]
Hi, sorry for the delay getting back to you.

What sort of [VoteVariationType](https://github.com/microsoft/electionguard-python/blob/main/src/electionguard/election.py#L71) are you trying to run?  The `votes_allowed` field is a holdover from the initial data structure port of the [Civics Common Standard Data Specification](https://developers.google.com/civics-data/reference/contest) to support future uses of cumulative voting.

The library currently only supports `one_of_m` (referendum) and `n_of_m` vote types, so you should be able to safely ignore the `votes_allowed` field.  It's possible we have an as-yet unidentified bug.  Can you share a sanitized version of your manifest?

**Comment by keithrfung** [comment]
Relevant issue but going to combine into a discussion since no action can quite be taken on this just yet.
https://github.com/microsoft/electionguard-python/issues/33
