### ISSUE TITLE
Windows Build failing due to gmp package path

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#262]
Windows build is incorrectly installing the locally referenced python gmp package

```
ERROR: Could not install packages due to an EnvironmentError: Invalid URL 'packages/gmpy2-2.0.8-cp38-cp38-win_amd64.whl': No schema supplied. Perhaps you meant http://packages/gmpy2-2.0.8-cp38-cp38-win_amd64.whl?

mingw32-make[1]: *** [Makefile:58: install-windows] Error 1
mingw32-make[1]: Leaving directory 'D:/a/electionguard-python/electionguard-python'
mingw32-make: *** [Makefile:25: install] Error 2
Error: Process completed with exit code 1.
```

[Example](https://github.com/microsoft/electionguard-python/runs/1627620313?check_suite_focus=true)

**Comment by jpic** [comment]
Rebasing on this branch did fix the build for #269 [before](https://github.com/microsoft/electionguard-python/pull/269/checks?check_run_id=1646745290) [after](https://github.com/microsoft/electionguard-python/pull/269/checks?check_run_id=1646771518)
