### ISSUE TITLE
Consider Json encoding Optional as null instead of None

### ISSUE THREAD

**Issue by JohnLCaron** [microsoft/electionguard-python#270]
Currently an Optional field that is empty is output as "None" in the Json serialization. Using null instead may have some advantages:

1. In Java, the GSON / Optional plugin (https://github.com/hsiafan/gson-java8-datatype) uses null, and barfs on "None". 

2. There are of course workarounds. Frankly I dont know if null is more standard than "None" since I havent used Json for serialization before. But the conversation on stack exchange makes me think null is a more obvious choice.

3. Using "None" forces an implementation to deal with Optional. This feels like it should be an implementation decision, and doesnt need to be in the common serialization format.

4. In Javaland, by convention an Optional is never null, and so there is no need to distinguish null from Optional.empty(). I dont know what the conventions in python are.

If accepted, the downside of this proposal is that the serialization format changes incompatibly. So I dont know if it's even possible to do so. But if your serialization format can still be changed, I think null is a better choice.

In any case, it might be wise to document the serialization format where needed, and add it to version control.

**Comment by danwallach** [comment]
+1 on this. To the extent that None might ever be serialized, it should be the JSON null token.

A more interesting question is whether None/null should ever appear on the wire. For example, in a JSON dictionary, rather than key:null, we could just leave the key out entirely. But what would that break?

**Comment by JohnLCaron** [comment]
AFAIU, leaving a field out of the serialization should be the same as explicitly encoding a null. Now that Ive said that, I should check what my code does. It seems likely that it simply leaves the object's default value, which may or may not be null. But I would be in favor of explicitly saying that no field = null for electionguard's json serialization. The main thing is to unambiguously specify it.

**Comment by keithrfung** [comment]
This is definitely a known issue and similar thought processes have been run through.

The underlying use of `jsons` seems to be problematic as a whole. This was problematic for Arlo as @danwallach mentioned as well as handling the models in the [python web api](https://github.com/microsoft/electionguard-web-api). We've discussed revisiting it, but it has to be done from a holistic approach.

**Comment by rc-ms** [comment]
I agree with @keithrfung and the discussion generally: we need a generic serialization approach. however this would be a breaking change that is non-trivial to implement holistically and needs to be planned for. we plan on drafting roadmap guidance soon and this will need to be addressed as part of that.
