### ISSUE TITLE
Missing lagrange coefficients to validate spec 10.

### ISSUE THREAD

**Issue by JohnLCaron** [microsoft/electionguard-python#281]
10. "An election verifier should confirm that for each trustee T_l serving to help compute a missing
share of a tally, that its Lagrange coefficient w_l is correctly computed by confirming the
equation (∏ j∈(U−{l}) j ) mod q = (w_l ⋅ (∏ j∈(U−{l}) (j − l) )) mod q."

Im not seeing the lagrange coefficient w_l "coefficient for use with shares of guardian T_l" stored in the election record. I would have guessed it would be in CiphertextCompensatedDecryptionSelection?

Apologies if Ive missed it.

**Comment by JohnLCaron** [comment]
These are my notes on dealing with this.

1. Lagrange coefficients are independent of which missing_guardian they are used for. 

So in decryption_mediator.py, line 67:

    _lagrange_coefficients: Dict[
        MISSING_GUARDIAN_ID, Dict[AVAILABLE_GUARDIAN_ID, ElementModQ]
    ] = field(default_factory=lambda: {})
    
 can be
 
        _lagrange_coefficients: Dict[AVAILABLE_GUARDIAN_ID, ElementModQ] = field(default_factory=lambda: {})
        
This simpler form is helpful since we have to store these in the Election Record.
This could be moved to a local variable in _get_plaintext_tally_, which simplifies the logic.

2. The Lagrange coefficients and the Guardian "sequence numbers" have to be stored in the Election Record. 

Here's a possible way to do that, in proto notation:

````
message PlaintextTally {
  string object_id = 1;
  map<string, PlaintextTallyContest> contests = 2;
  map<string, PlaintextTallyContestMap> spoiled_ballots = 3;

  //added
  map<string, ElementModQ> lagrange_coefficients = 4;
  repeated GuardianState guardian_states = 5;
}

message GuardianState {
  string guardian_id = 1;
  uint32 sequence = 2;
  bool missing = 3;
}
````
The lagrange_coordinates and list of guardian states can both be computed and passed to the PlaintextTally constructor, all in _DecryptionMediatoer.get_plaintext_tally()_.

3. The Guardian "sequence numbers" cant be zero. 

The sequence numbers are actually the x_i coordinates of the lagrange polynominal, not just a simple index. So they must be > 0. This only shows up when creating the Guardians, which I guess is an external call, but it does happen in _test_end_to_end_election.py_, line 167:

````
        # Setup Guardians
        for i in range(self.NUMBER_OF_GUARDIANS):
            self.guardians.append(
                Guardian("guardian_" + str(i), i, self.NUMBER_OF_GUARDIANS, self.QUORUM)
            )

change to 

        # Setup Guardians
        for i in range(self.NUMBER_OF_GUARDIANS):
            self.guardians.append(
                Guardian("guardian_" + str(i), i + 1, self.NUMBER_OF_GUARDIANS, self.QUORUM)
            )
````

Its an easy mistake to make, so probably should check it in the Guardian constructor. I am running this understanding by @benaloh, to make sure I have it right.

**Comment by benaloh** [comment]
Here are some basic principles of guardian numbering.

•	The numbering of the n guardians should be 1,2,3,…,n.
•	There should NOT be a guardian number 0.  This would be a substantial breach as this guardian would hold a “master” secret that would make the other guardians unnecessary!
•	There is no harm to using non-consecutive values for guardians, but there is no security benefit whatsoever; and smaller values make the computations more efficient.
•	The computation of Lagrange coefficients depend only the indices of the quorum of guardians that are present and used for decryption.  Note that if more than a quorum are present, the assumption is that only a quorum are used.  It should work mathematically to use all guardians present if they exceed a quorum, but this just increases the computation to achieve the same result.

**Comment by JohnLCaron** [comment]
On review, the proposal 2 above (lagrange_coordinates and list of guardian states saved in the PlaintextTally object) is rather clumsy. 

We only need to save each available guardian's lagrange_coordinate and sequence number once, so its cleaner to just add it to the election record rather than to the tally.

I looked at skipping storing the lagrange_coordinate's altogether, since they are easy to calculate, but then there's nothing to validate for spec #10. I assume we should just follow the spec.

So instead of the above, I propose we add something like the following added to the election record during the decryption phase, one for each available guardian:

````
class AvailableGuardian(Serializable):
    guardian_id: GUARDIAN_ID
    sequence: int
    lagrange_coordinate: ElementModQ
````

which will allow spec #10 to be validated. 

Im not crazy about the word "sequence", it should be more like "x_coordinate", but i'll leave it for consistency with the current code.

**Comment by benaloh** [comment]
I'm concerned that we're making this more complicated than it needs to be.

If a guardian is missing during decryption, a quorum of the remaining guardians must each apply a share of the missing guardian's private key.  Each guardian in the quorum uses its share of the missing guardian's key exactly as though it is its own key.  To perform this computation, each guardian in the quorum must know which guardian is missing, but need not know anything about the other guardians in the quorum and NEED NOT COMPUTE LAGRANGE COEFFICIENTS.  The computation of Lagrange coefficients is outside of the guardian responsibilities.

Whoever is marshalling the election record for publication (the mediator, the election administrator, etc.) can see which guardians are present and compute the Lagrange coefficients as part of the election record.  Strictly speaking, the Lagrange coefficients don't need to be published at all -- instead, we could leave it to verifiers to compute Lagrange coefficients on their own and match the tally; however, it's better that "we" compute and publish the Lagrange coefficients and let verifiers confirm our computations.  (This is no different than our multiplying the partial decryptions to form the full decryption.)

We could even proactively shortcut this process by having each guardian apply its share of each other guardian's private key and report the result along with the result of applying its own private key.  I don't believe that this introduces any privacy/confidentiality issues.  However, this would increase the computation and data publication by a factor of the number of guardians -- producing lots of additional computation and data that are superfluous except in the rare case that one or more guardians doesn't complete its tasks.

**Comment by JohnLCaron** [comment]
Im not looking at the math, just looking at the current code.

The **DecryptionMediator** does compute lagrange coefficients and passes them to **Decryptions**._reconstruct_decryption_share__() which calls _reconstruct_decryption_contest_() for each contest. These are used to compute the _reconstructed_share_ for each selection in the contest. This is all placed in the **DecryptionShare** used by **DecryptWithShares.decrypt_tally**(). 

Not sure if thats an inconsistency or not with what you said above, but can investigate further if you want.

I investigated the verifier computing the lagrange coefficients itself, but then the validation becomes (almost) a tautology.

**Comment by benaloh** [comment]
It's true, the verification steps involving the Lagrange coefficients should just duplicate the mediator steps in computing same.

I apologize if I misunderstood the concerns.  In a typical election, the mediator is tasked with taking the published partial decryptions from the guardians and publishing the product.  In an election with a missing guardian, the mediator also takes the published "recovery" partial decryptions, computes the appropriate Lagrange coefficients and from that the missing partial decryption, and publishes all of that as well.

**Comment by JohnLCaron** [comment]
Yes, sorry I misunderstood your post. The Guardians do not compute the lagrange coefficients, the DecryptionMediator does.

**Comment by JohnLCaron** [comment]
@benolah are you saying that the verifier should just do its own calculation of the Lagrange coefficients, and its not necessary that the Lagrange coefficients are part of the election record? 

Currently the [spec describing the election record](https://www.electionguard.vote/spec/0.95.0/8_The_election_record/) specifies storing the "Lagrange coefficients used for replacement of any missing partial decryptions (if any)".

Assuming that an independent verification is needed, then the python library still needs to have the Lagrange coefficients added to the election record.

In the electionguard-java JSON serialization, these are put into 

 **lagrange_coordinates/available_guardian<guardian_id>.json**

They cant be written until the decryption stage, when its know which guardians are available and which are missing.

**Comment by JohnLCaron** [comment]
@benolah are you saying that the verifier should just do its own calculation of the Lagrange coefficients, and its not necessary that the Lagrange coefficients are part of the election record? 

Currently the [spec describing the election record](https://www.electionguard.vote/spec/0.95.0/8_The_election_record/) specifies storing the "Lagrange coefficients used for replacement of any missing partial decryptions (if any)".

Assuming that an independent verification is needed, then the python library still needs to have the Lagrange coefficients added to the election record.

In the electionguard-java JSON serialization, these are put into 

 **lagrange_coordinates/available_guardian<guardian_id>.json**

They cant be written until the decryption stage, when its know which guardians are available and which are missing.

**Comment by benaloh** [comment]
This is a subtle point that should be more clearly described.  The guardians don't need to know or do anything with Lagrange coefficients; they only need to know which guardian(s) is/are missing.  The election manager needs to select a quorum set of remaining guardians for which to compute Lagrange coefficients which will then be used to complete the decryptions.

Specifically, at the time the guardians perform their "recovery" operations, they need to know which guardian(s) is/are missing, but they do not need to know which other guardians are participating in the recovery process.  So, for example, if we have five guardians and a quorum size of three, and if Guardian 2 is missing at decryption time, then (at least three of) the remaining guardians are asked to compute a partial decryption for missing Guardian 2.

The Lagrange coefficients for a quorum of participating guardians is then computed by the election manager and used to complete the tally computation.  So to continue the prior example, only three of the four remaining guardians are needed to complete the decryption.  The election manager should include in the record (at least) three of the partial decryptions for missing Guardian 2 together with the Lagrange coefficients used to complete the decryption.

An argument could be made for taking a minimalist approach.  As long as a sufficient number of recovered partial decryptions are posted, a verifier could choose any subset which achieves the quorum, compute the associated Lagrange coefficients, and complete the decryption.  Since suitable Lagrange coefficients should be computed by a verifier, they needn't be explicitly written into the election record.  Indeed, if more than a quorum of recovered partial decryptions are posted, a verifier may select a different subset and compute different Lagrange coefficients to complete the decryption.  However, the approach that we've taken is to overpublish.  So the election manager should explicitly write into the election record the Lagrange coefficients that it computed and used to complete the decryption, and verifiers can independently re-compute these same Lagrange coefficients, match them with the record, and use them to verify the decryption.

**Comment by keithrfung** [comment]
I'm gonna close this issue out following @benaloh 's comment.

**Comment by keithrfung** [comment]
I misunderstood @benaloh 's comment here.

I'm going to reopen and this will be the followup. 

We will create a `LagrangeCoefficientRecord` that can be produced.
