### ISSUE TITLE
Unused functionality in Guardian

### ISSUE THREAD

**Issue by JohnLCaron** [microsoft/electionguard-python#303]
## Issue

**Description**
It appears that the functionality associated with _ElectionPartialKeyVerification_ has moved to _KeyCeremonyMediator_, and is not needed in _Guardian_.

So the field _guardian_election_partial_key_verifications_ and associated methods in Guardian can be removed. 

Same with Guardian.publish_joint_key() - not used in favor of KeyCeremonyMediator.publish_joint_key(), AFAICT.

**Comment by keithrfung** [comment]
These are not unused. @benaloh can comment on this, but I'll try to explain.

The `Mediator` named classes are convenience classes but not the ONLY way to generate the keys. 

For example, 5 guardians can use a mediator to ease the key ceremony process BUT they should be able to do the same process WITHOUT the mediator. There is no requirement for the mediator to exist. This means any Guardian should be able to create the joint key. 

The same goes with the partial key verificiations. This should be feasible without a mediator.

**Comment by benaloh** [comment]
Yup.  This isn't a crypto/security issue -- it's just logistics.  The guardians can share their public keys by pairwise communication and agreement protocols or by using a mediator.  As an optimization, if there is no thresholding (all guardians are required for decryption), the whole key establishment ceremony can be skipped in favor of each guardian simply publishing its public key.  (But the robustness offered by thresholding is very valuable and should almost certainly be used in any substantial election.)
