### ISSUE TITLE
Generalizing how decryption of ballots and inclusion of proofs works

### ISSUE THREAD

**Issue by danwallach** [microsoft/electionguard-python#306]
**Description**
Cryptographically, when the trustees produce a plaintext value, they should also produce a proof that the plaintext and the original ciphertext correspond to one another. This is typically done with a Chaum-Pedersen proof.

The original ElectionGuard-Python code does this in `decryption_share.py`. It would be handy to have a simplified version that works with singular decryption keys, and a general-purpose data structure that works and is testable under both use cases.

Meanwhile, the VotingWorks fork of ElectionGuard-Python does all of this, assuming a single private key, but not integrated in any way with the trustee support.

Proposal: we need a grand-unified infrastructure that works for decrypting individual ballots, with or without trustees, and which also works in a unified way with *tallies*, which have some cryptographic similarities with ballots, but are really different animals altogether.

Pointers to the VotingWorks fork below.

Decryption proof: 
- https://github.com/votingworks/electionguard-python/blob/4bcc0cb79b31080fd02bf589f538a9f2b2d74f87/src/electionguard/chaum_pedersen.py#L690-L753
- This code also tries to tease out a "generic" Chaum-Pedersen proof object from the various specific ways in which it might be used, or at least represents the starting point of such a "generic" proof object, e.g., where you can ask the proof object to do a check without necessarily validating the hash result (c), because you need to handle that differently in disjunctive proofs.

Ballot decryption with proofs: 
- https://github.com/votingworks/electionguard-python/blob/4bcc0cb79b31080fd02bf589f538a9f2b2d74f87/src/electionguard/decrypt_with_secrets.py#L70-L147
- https://github.com/votingworks/electionguard-python/blob/4bcc0cb79b31080fd02bf589f538a9f2b2d74f87/src/electionguard/decrypt_with_secrets.py#L239-L297
- https://github.com/votingworks/electionguard-python/blob/4bcc0cb79b31080fd02bf589f538a9f2b2d74f87/src/electionguard/decrypt_with_secrets.py#L423-L493

Tally decryption with proofs (note: very different data types):
- https://github.com/votingworks/arlo-e2e/blob/40e3fcbd214832faf713eeef5e34677d889c0ae3/src/arlo_e2e/tally.py#L224-L249

**Comment by keithrfung** [comment]
Closing this for now, may be reopened later or opened as smaller tickets
