### ISSUE TITLE
Support for Arch/ Arch based systems when using make to build locally.

### ISSUE THREAD

**Issue by OBITORASU** [microsoft/electionguard-python#328]
## Feature Request
**Description**
Add support for Arch and Arch based systems when building locally using make.
Currently the Debian and Debian based systems are supported when using ```make``` to build locally, due to theselines:
```
install-gmp-linux:
	@echo 🐧 LINUX INSTALL
	sudo apt-get install libgmp-dev
	sudo apt-get install libmpfr-dev
	sudo apt-get install libmpc-dev
```
Any distro not using ```aptitude``` as their default package managers will face errors in these lines when trying to build locally. This works well considering a lot of the developers stick to Debian and/or Debian based distros like Ubuntu, but it would be really good if we added support for Arch and Arch based systems (like Manjaro which is also popular among developers these days) by default. I think a simple ```sudo pacman -S gmp``` should do the job. The package information is present [here](https://archlinux.org/packages/core/x86_64/gmp/) do check it out if you are considering this feature request. Thank you!

**Comment by keithrfung** [comment]
This is def something we want to do. However, this is a duplicate issue.
See https://github.com/microsoft/electionguard-python/issues/257

**Comment by OBITORASU** [comment]
Thanks for the feedback!

**Comment by keithrfung** [comment]
Anytime! We'd love to see a PR on this. Feel free to move your comments to #257 and take a crack at it.
