### ISSUE TITLE
Encrypt `extended_data`

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-python#35]
The `PlaintextBallotSelection` includes an `extended_data` field that should be encrypted and decrypted.

Question: The encryption method should be able to support string lengths up to 256? or 256 bits?

In order to make the ballots homogenous, extendedData values are wrapped in an internal data structure and padded to max length. The first 4 characters are reserved for the length, and then the string follows. 
 if no data is passed in the extended data field, then random data is generated to fill the field and it is keyed specifically to be identified as random data.

For instance, something like this:

1. extendedData in: `some write in candidate name`, extended data out: `028:some write in candidate name_gj8749hg8g55h98...` where 028 is the character count of the real data
2. extendedData In: `(an empty string)`, extendedData out: `000:_jh7453h7egnu9...`

as an alternative we could use ore reuse some binary serialization mechanism and then encrypt the serialized value?

suggestions welcome

**Comment by keithrfung** [comment]
The current thought is the default version of this will use a python package using AES encryption for performance. 
https://pypi.org/project/cryptography/ seems to be the optimal package with downloads in the millions.

**Comment by keithrfung** [comment]
https://github.com/microsoft/electionguard-python/issues/47
