### ISSUE TITLE
CiphertextBallot crypto_hash_with does not enforce ordering

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-python#350]
## Bug Report

**Expected Behavior**

When generating crypto hashes on ciphertext ballots, the hashes should always be created in the same order

in [ballot.py#CiphertextBallot.crypto_hash_with](https://github.com/microsoft/electionguard-python/blob/main/src/electionguard/ballot.py#L743):

```python
contest_hashes = [contest.crypto_hash for contest in self.contests]
```
and in [ballot.py#_ciphertext_ballot_context_crypto_hash](https://github.com/microsoft/electionguard-python/blob/71e8150e3f622de1f1c6cb177bd7b7e954150943/src/electionguard/ballot.py#L540)

```python
selection_hashes = [selection.crypto_hash for selection in ballot_selections]
```

**Actual Behavior**

we assume the order is correct, however if the user generated the encryptions using the functional interfaces (and not the `encrypt_ballot` function) there is no way to guarantee.

**Proposed Solution**

Add the `sequence_order` of each `SelectionDescription` and each `ContestDescription` from the `InternalManifest` to the expected required values of each object constructor and make function.  This solution retains the separation of the ballot from the manifest.:

e.g.:

```python
def make_ciphertext_ballot_selection(
    object_id: str,
    description_hash: ElementModQ,
    ciphertext: ElGamalCiphertext,
    elgamal_public_key: ElementModP,
    crypto_extended_base_hash: ElementModQ,
    proof_seed: ElementModQ,
    # **** DEV: add the sequence order ****
    sequence_order: int,
    selection_representation: int,
    is_placeholder_selection: bool = False,
    nonce: Optional[ElementModQ] = None,
    crypto_hash: Optional[ElementModQ] = None,
    proof: Optional[DisjunctiveChaumPedersenProof] = None,
    extended_data: Optional[ElGamalCiphertext] = None,
) -> CiphertextBallotSelection:
```

and:

```python
@runtime_checkable
class CiphertextSelection(Protocol):

    object_id: str

    # **** DEV: add the sequence order ****
    sequence_order: int

    description_hash: ElementModQ
    """The SelectionDescription hash"""

    ciphertext: ElGamalCiphertext
    """The encrypted representation of the selection"""
```

then something like:

```python
selection_hashes = [
    selection.crypto_hash for selection in sorted(
        ballot_selections, key=lambda c: c.sequence_order
    )]
```

and repeat for contests, etc.  This code change will ripple through a number of files including `encrypt.py`.

also, `ballot.py#_ciphertext_ballot_context_crypto_hash` should probably be renamed to `ballot.py#_ciphertext_ballot_contest_crypto_hash` (**contest** and not _context_)

**Comment by keithrfung** [comment]
This bug directly relates to this one mentioned by @JohnLCaron 
https://github.com/microsoft/electionguard-python/issues/343
