### ISSUE TITLE
Issue in make command

### ISSUE THREAD

**Issue by sheriumair** [microsoft/electionguard-python#351]
When I run make command, I get the following error. The below attached code the part from where the error occurs

🔧 INSTALL
poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing gmpy2 (2.0.8): Failed

  EnvCommandError
  Command ['/home/sheriub/.cache/pypoetry/virtualenvs/electionguard-QxNRXeI4-py3.8/bin/pip', 'install', '--no-deps', 'file:///home/sheriub/.cache/pypoetry/artifacts/86/df/2e/cc208da757a001f2bc1cf1826bcd945839a6cf622b89cc85dec599fd03/gmpy2-2.0.8.zip'] errored with the following return code 1, and output: 
  Processing /home/sheriub/.cache/pypoetry/artifacts/86/df/2e/cc208da757a001f2bc1cf1826bcd945839a6cf622b89cc85dec599fd03/gmpy2-2.0.8.zip
  Building wheels for collected packages: gmpy2
    Building wheel for gmpy2 (setup.py): started
    Building wheel for gmpy2 (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:

**Comment by keithrfung** [comment]
This is not an error. gmp is not seen as installed.
