### ISSUE TITLE
🚧  Reconstruction of Guardian

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#355]
## Original Issue

**Description**
The stateful `Guardian` class after the latest refactor is used to both run the Key Ceremony and create their decryption shares. Since these two pieces may exist over vastly different times this brings together the question of reconstructing the `Guardian`. The best way to proceed forward with this seems to allow a constructor or a factory method to reconstruct the guardians. 

~~This would need specifically to include most of the information in the `PrivateGuardianRecord`.~~

~~So two options to move forward on this:~~
~~1. Create a constructor with optionals to allow a guardian to be constructed with ElectionKeyPair, AuxiliaryKeyPair, sent and received ElectionPartialKeyBackups~~
~~2. Use a factory method to build a guardian and utilize the save and receive to consume a PrivateGuardianRecord to rebuild that guardian with the necessary information~~

------------------------------------------------------

## Updated Information 

When reconstructing the guardian it can be tempting to use the nonce, instead the correct methodology should be having the `ElectionKeyPair` as a parameter the `Guardian` instead of the nonce.

The nonce can be seen here:
https://github.com/microsoft/electionguard-python/blob/03698c683ab35f608e35dc9b66217caa1d40f7eb/src/electionguard/guardian.py#L157

But here we can notice that it is only used to create an `ElectionKeyPair`
https://github.com/microsoft/electionguard-python/blob/03698c683ab35f608e35dc9b66217caa1d40f7eb/src/electionguard/guardian.py#L177

### Implementation

There is a PrivateGuardianRecord that holds this info, but the simplest way is:
- [ ] Add a get_key_pair() to the Guardian and saving that file. 
- [ ] Remove the nonce seed from the init and replace with mandatory ElectionGuardKeyPair
- [ ] Use @classmethod to implement the nonce and other constructors.

The `get_key_pair` could eventually be changed to a `export_secret_key` if necessary to get the math value for saving on items like Yubikeys.

```py
class Guardian

    def __init__(
        self,
        id: str,
        sequence_order: int,
        number_of_guardians: int,
        quorum: int,
        key_pair: ElectionKeyPair,
    ) -> None:
        ...

    @classmethod
    def from_nonce(..., nonce: ElementModQ = None)
         """An optional `ElementModQ` value for nonce that can be used to generate the `ElectionKeyPair`. It is recommended to only use this field for testing"""
        generate_election_key_pair(id, sequence_order, quorum, nonce)
         return cls(..., key_pair)

    def get_key_pair(self) -> ElectionKeyPair:
          pass
 ```

**Comment by lmarie79** [comment]
@keithrfung - is this card still in play? If so, do we need community help?

**Comment by keithrfung** [comment]
This issue is nonspecific or too large. This makes it difficult for developers to resolve. Subsequently, we are closing the issue. However, topics of this issue could be opened as new more precise or specific issue(s).
