### ISSUE TITLE
test_decryption_mediator.py takes forever to execute

### ISSUE THREAD

**Issue by syedalihasany** [microsoft/electionguard-python#361]
after running the command `make` all dependencies get installed correctly but after the test session starts the file `test_decryption_mediator.py` keeps on running. I have Ubuntu 20.04 installed and everything else works fine apart from this. I hope someone can help me with this.

**Comment by keithrfung** [comment]
The workflow that we runs on the latest version of Ubuntu
https://github.com/microsoft/electionguard-python/blob/a5232f12ce647622528e46f3b2c25ff10d7bcdbe/.github/workflows/pull_request.yml#L13

This tests takes the longest to run but it should finish at some point. This can be evidenced by the GitHub Action itself. Here's an example of it running.
![Screen Shot 2021-04-26 at 11 37 26 AM](https://user-images.githubusercontent.com/10125297/116110561-ccb0d680-a683-11eb-90dd-8e041e4f3620.png)
Source: https://github.com/microsoft/electionguard-python/runs/2403447505?check_suite_focus=true

Can you give better specifics? Use this and `@skip` to skip certain tests. Isolate which one is actually causing the problem. 
`poetry run pytest tests/property/test_decryption_mediator.py`

I tested it locally on my machine. 
![Screen Shot 2021-04-26 at 11 40 15 AM](https://user-images.githubusercontent.com/10125297/116110971-2f09d700-a684-11eb-9a8c-e590f5f49e27.png)

**Comment by keithrfung** [comment]
I should also mention this comment in a previous similar issue
https://github.com/microsoft/electionguard-python/issues/220#issuecomment-706581492

**Comment by keithrfung** [comment]
I'm going to close this issue, but the long term fix is actually going to be to use smaller primes during testing for faster decryption (See #89 ).
