### ISSUE TITLE
types.py module has naming conflict creating a "MappingProxyType"

### ISSUE THREAD

**Issue by syedalihasany** [microsoft/electionguard-python#362]
## ImportError: cannot import name 'MappingProxyType' from 'types' 

**This error is returned when running the command  `python election.py` or `python manifest.py`**

The error is probably due to python not recognizing the `types.py` file in the directory `electionguard-python-main/src/electionguard` where the rest of the files are also present e.g. `election.py` and `manifest.py`

**Comment by keithrfung** [comment]
The long term fix to this is refactoring `types.py`. This should solve the issue very quickly. Renaming this issue to assist in users being able to resolve this issue. 

[Source](https://stackoverflow.com/questions/43453414/cannot-import-name-mappingproxytype-error-after-importing-functools)

**Comment by soham4abc** [comment]
I am willing to work on this issue. But, I have a question "do we need to rename the `types.py`?
