### ISSUE TITLE
Remove Election Manifest Schema methods and file

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#384]
## Issue

**Description**
These should get migrated from electionguard python to the api and root project. 

The long term strategy is to handle the spec check at the top level and the spec itself should be defining these json schemas instead of the python repository. 

https://github.com/microsoft/electionguard-python/blob/main/src/electionguard/election_description_schema.json
https://github.com/microsoft/electionguard-python/blob/main/src/electionguard/schema.py

**Comment by bhushan-borole** [comment]
Hey @keithrfung 
I would like to work on this issue.
Could you please elaborate on this?

**Comment by keithrfung** [comment]
@bhushan-borole Sorry I missed this. I already picked it up and knocked it out. There is an accompanying PR on the `electionguard-python-api` repo if you'd like to take that.

**Comment by bhushan-borole** [comment]
@keithrfung Sure I will look into it.
