### ISSUE TITLE
✨ Election Configuration of Edge Cases

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#386]
## Feature Request

**Description**
A system for handling allowing or disallowing of certain edge cases.
Examples includes:
- null votes
- undervotes
- overvotes

**Expected Solution**
Currently, the only concern is handling overvotes. A `Config` will be added to the `Context` allowing overvotes to be enabled. This can then be part of setting up the election

For example:
```
class Config():
      allow_over_votes: bool
```

The `Config` itself should have a constructor that defaults to current supported setup.
```py
allow_over_votes: False
```

If another option is selected other than these, they should throw a NotImplemented with a message indicating that the feature is not available, until the feature is implemented.

**Comment by keithrfung** [comment]
There might be some discussion around the name `Config` perhaps it would be worthwhile to have something a bit more specific.

**Comment by rc-ms** [comment]
i like this approach. where should we codify it?
