### ISSUE TITLE
Reorganize and refactor `electionguardtest` to `electionguard-tools`

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#401]
## Feature Request

**Description**

**Rename**
`electionguardtest` has increased in size gradually to include more items than just testing items. 
`tools` or `utils` seems more accurate. 

**Reorganize**
![Screen Shot 2021-07-26 at 4 27 27 PM](https://user-images.githubusercontent.com/10125297/127054493-b449b9eb-1199-49ba-9a1f-6c1a908bab88.png)
```
/electionguard-tools
---- __init__.py
----/strategies
-------- __init__.py
-------- election.py
-------- elgamal.py
-------- group.py
----/factories
-------- __init__.py
--------ballot_factory.py
--------election_factory.py
----/helpers
-------- __init__.py
-------- sample_generator.py 
-------- key_ceremony_orchestrator.py <-- key_ceremony_helper
-------- tally_ceremony_orchestrator.py <--- decryption_helper
-------- tally_accumulate.py <--- tally
```
The inner folder __init__ should all be sure to import and therefore export the inner files. For example, for init py in strategies

```

...
from .election import *
from .elgamal import *
from .group import *
```

This should assist with some import statements. The goal is to give more meaningful usings like
`from electionguard-tools.strategies import elgamal_keypairs, elements_mod_q_no_zero`

This will have an incredible amount of updates across the entire repository due to the imports but hopefully will help long term.

**Comment by soham4abc** [comment]
I am willing to work on this issue! If possible pls assign!
