### ISSUE TITLE
♻️ Single source the version from pyproject.toml

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#422]
# Feature Request

`__version__` should be present in the __init__.py of `electionguard` and `testelectionguard`

This shouldn't be duplicated and should run off the pyproject.toml version.
Here is an [example](https://gist.github.com/benkehoe/066a73903e84576a8d6d911cfedc2df6).

**Comment by ronnie-llamado** [comment]
@keithrfung I'm currently looking at this issue. 

Is there a need to support Python pre-3.8 like in the example? In the `README`, Python 3.9.5 is specified, but are there plans to eventually support pre-3.8 python versions?

https://github.com/microsoft/electionguard-python/blob/eb19846cd17ae73064586da8f0be11d97c565b43/README.md#L32-L38

**Comment by keithrfung** [comment]
Hey @ronnie-llamado getting back to this a bit late, but ideally yes we would like to support some pre 3.8 versions. The biggest reason we lock the version is related to the windows build where we need the precompiled gmp libraries.
