### ISSUE TITLE
🐛. Pip needs to be upgraded before tasks.

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#425]
## Bug Report

**Expected Behavior**
On initial `make` there should be minimal difficulties for new users.

**Actual Behavior**
If pip isn't upgraded installs will fail and this provides a worse experience for individuals. 

**Solution**
`python -m pip install -U pip` should be added to the make. This is the safe command that should work on Windows. 
At this line: https://github.com/microsoft/electionguard-python/blob/6ecf69919e62c8a9e7d850cbd54470a84281e855/Makefile#L13

**Comment by Jayita10** [comment]
Hi, I want to work on this issue, please assign me

**Comment by Jayita10** [comment]
I was quite willing to work on this issue @DeviousLab :|

**Comment by keithrfung** [comment]
@Jayita10 It's okay. There's more than enough issues for everyone. 😃 

On the weekends, we can't always assign the issues. Lead with working them first. 
Smaller issues tend to get picked up quickly.

**Comment by keithrfung** [comment]
@Jayita10 Here's a quick issue, if you'd like one on our `cpp` repo: https://github.com/microsoft/electionguard-cpp/issues/204

**Comment by Jayita10** [comment]
Yeah sure :)
