### ISSUE TITLE
✅. Verifier Package: Verify Aggregation

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#428]
## Feature Request

**Dependency**
Requires #426 to be complete.

**Description**
Create a verify method to verify that all the ballots are aggregated correctly into the encrypted tally. 
Method should be added to the Verifier package from #426. 

- [ ] Create `verify_aggregation` method
- [ ] Create accompanying test

------------

Submitted ballots (`SubmittedBallot`) are aggregated into an aggregate ballot aka a Tally (`CiphertextTally`) during an election. This verify method will take all the `SubmittedBallot` and add them to create a `CiphertextTally`. This can then be compared. 

```py
def verify_aggregation(submitted_ballots: List[SubmittedBallot], tally: CiphertextTally) -> Verification
       # Add Submitted Ballots to create a CiphertextTally
       # Compare Equality of Tallies
       # Return VerificationResult with info
```

```py
@dataclass
class Verification
      verified: bool
      message: Optional[str]
```

This can reference the electionguard package to do the aggregation.
https://github.com/microsoft/electionguard-python/blob/eb19846cd17ae73064586da8f0be11d97c565b43/src/electionguard/tally.py#L228-L230

**Comment by PradyumnaKrishna** [comment]
I'd like to take this.

Just want to know how can equality of these tallies can be compared since these tallies can have different Id.

**Comment by keithrfung** [comment]
@PradyumnaKrishna This comment slipped right by me. You can manually overwrite the ID if you're looking for an easy comparison. The concern is actually not equality of the tally as in id but actually the values aggregated.

**Comment by PradyumnaKrishna** [comment]
What about checking that tally contains all the ballots

```python3
def verify_aggregation(submitted_ballots: List[SubmittedBallot], tally: CiphertextTally) -> Verification
    for ballot in submitted_ballots:
        if ballot not in tally:
            return Verification(False)
    ...
```
