### ISSUE TITLE
✅. Verifier Package: Verify Decryption

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#429]
## Feature Request

**Dependency**
Requires #426 to be complete.

**Description**
Create a verify method to verify that a spoiled/challenge ballot or an aggregate ballot / tally has been correctly decrypted. 
Method should be added to the Verifier package from #426. 

Methods should take a `PlaintextTally`. This should be accomplished by checking the proofs within this Tally that resulted from the Decryption. 

- [ ] Create `verify_decryption` method
- [ ] Create accompanying test

---------------

A `SubmittedBallot` that has been spoiled/challenged or a `CiphertextTally` are typically decrypted. These both result in a `PlaintextTally`.

A `ChaumPedersenProof` should be within a `CiphertextDecryptionSelection`
https://github.com/microsoft/electionguard-python/blob/eb19846cd17ae73064586da8f0be11d97c565b43/src/electionguard/decryption_share.py#L76-L79

This can be found in the lowest level of the `PlaintextTally`
https://github.com/microsoft/electionguard-python/blob/eb19846cd17ae73064586da8f0be11d97c565b43/src/electionguard/tally.py#L25-L37

For this work, these proofs just need to be checked using the decrypted value. 
```py
def verify_decryption(decrypted_tally: PlaintextTally) -> Verification:
       # Check proofs
       # Return Validation 
```

**Comment by PradyumnaKrishna** [comment]
I would like to take this now, I want to ask that this `PlaintextTallySelection` have `value`, `message`, and `shares` and this verifier need to checks the proofs of these `shares` but to check the proof it requires to have three fields.

Referring to this method
https://github.com/microsoft/electionguard-python/blob/eb19846cd17ae73064586da8f0be11d97c565b43/src/electionguard/decryption_share.py#L90-L95
`election_public_key` is may be the `value` of `PlaintextTallySelection` but what is the `extended_base_hash`.
