### ISSUE TITLE
🐞  Incorrectly referenced tuple format in Chaum Pedersen Bench

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Benchmark will fail with this error
![Screen Shot 2021-09-22 at 12 55 20 PM](https://user-images.githubusercontent.com/10125297/134388372-9fdeaeb5-54b3-4d72-a2ba-4502fa32a358.png)
. 

### Expected Behavior

Benchmark should properly run. 

### Steps To Reproduce

1. run `make bench`

### Environment

```markdown
- OS: Any
```

### Anything else?

https://github.com/microsoft/electionguard-python/blob/740b7d0f145261a856706b08e1e13324021813af/tests/bench/bench_chaum_pedersen.py#L34
Removing the tuple line and replacing the code seems like the fastest approach. 

```
ciphertext = get_optional(elgamal_encrypt(0, bi.r, bi.keypair.public_key))
start1 = timer()
proof = make_disjunctive_chaum_pedersen_zero(
    ciphertext, bi.r, bi.keypair.public_key, ONE_MOD_Q, bi.s
)
```

**Comment by sshiv5768** [comment]
I want to work on this issue.

**Comment by sshiv5768** [comment]
Hey, @keithrfung can your share some resources to get an idea from where should i start.

**Comment by keithrfung** [comment]
@sshiv5768 The card actually shows the exact line that is the problem. It's shown as a tuple but it's actually a dataclass object. Line 34 shouldn't exist and it should be referenced as properties.
