### ISSUE TITLE
✨ Use of var-args makes translation to other languages difficult

### ISSUE THREAD

**Issue by axman6** [microsoft/electionguard-python#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

There seems to be some inconsistent use of varargs in a few places that make the translation to other languages more difficult than it needs to be. The example I've come across is https://github.com/microsoft/electionguard-python/blob/main/src/electionguard/ballot.py#L757 which has the lines 

```python
        contest_hashes = [contest.crypto_hash for contest in self.contests]
        return hash_elems(self.object_id, encryption_seed, *contest_hashes)
```

### Possible Implementation

The code above could easily just be simply

```python
        contest_hashes = [contest.crypto_hash for contest in self.contests]
        return hash_elems(self.object_id, encryption_seed, contest_hashes)
```

which should achieve the same outcome but make translations easier when languages don't have things like heterogeneous lists. In my Haskell implementation, hashes of multiple arguments of differerent are represented using the instances for various tuple types, so I can't generate a tuple of arbitrary size at runtime.

**Comment by keithrfung** [comment]
This is a great distinction to make for transliteration. Let's leave this in `triage` but expand a bit more to denote all the lines where this is true.

**Comment by keithrfung** [comment]
@axman6 Going to move this out of triage. If you have any lines you'd like to denote here for others to grab, I think this is a great move to allow easier transliteration for others.

**Comment by subhamgcon** [comment]
Hey, I am a beginner and this is my first hacktoberfest. I am currently learning how to code properly but I really want some hands on experience and I love contributing to open source. Could you explain me what this issue all about and how can I fix it?? I want to work on it. @keithrfung

**Comment by keithrfung** [comment]
@subhamgcon No problem. I got you. I removed the `good-first` issue on this label but I'll give an explanation of what this would look like. 

The concern is that we use [var-args](https://www.geeksforgeeks.org/args-kwargs-python/) which is difficult to transliterate, meaning difficult to port to other languages. We could opt for a builder pattern or sending arrays to ensure this would not be necessary. 

I did a quick cursory search and due to `hash_elems` this ripples to a good number of functions. 
![Screen Shot 2021-10-05 at 10 06 17 AM](https://user-images.githubusercontent.com/10125297/136039315-8903d48b-cf67-449a-b49c-9a260c64cc9f.png)

**Comment by subhamgcon** [comment]
> @subhamgcon No problem. I got you. I removed the `good-first` issue on this label but I'll give an explanation of what this would look like.
> 
> The concern is that we use [var-args](https://www.geeksforgeeks.org/args-kwargs-python/) which is difficult to transliterate, meaning difficult to port to other languages. We could opt for a builder pattern or sending arrays to ensure this would not be necessary.
> 
> I did a quick cursory search and due to `hash_elems` this ripples to a good number of functions. ![Screen Shot 2021-10-05 at 10 06 17 AM](https://user-images.githubusercontent.com/10125297/136039315-8903d48b-cf67-449a-b49c-9a260c64cc9f.png)

Okay, I understood so how could I fix this please explain?

**Comment by subhamgcon** [comment]
> @subhamgcon It's an issue with the variable arguments.
> 
> So python uses `method(*items)` so you can call the method such that `method(item1, item2)` or `method(item1, item2, item3)` works.
> 
> The solutions can be changed by creating a list or using a builder pattern. For example:
> 
> ```python
> def method(items: List[Item])
>     ....
> 
> list = [item1, item2, item3]
> method(list)
> ```

Okay!! Can I work on it now?

**Comment by keithrfung** [comment]
This feature won't be worked on despite the value of transliteration because we want to make sure the hashes are as flat as possible going for.
