### ISSUE TITLE
Refactor CiphertextBallot and CiphertextAcceptedBallot relationship

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-python#45]
In the current implementation, the `CiphertextAcceptedBallot` inherits directly from the `CiphertextBallot` however this relationship is not correct since the `CiphertextAcceptedBallot` should not have a `nonce` field for itself or any `contest` or `selection` and it should also require that the `proof` field is required for each `contest` and `selection`.

Proposed solution:

create a `CiphertextBallotBase` which other elements can derive from.  Similarly, refacotrs will need to be completed for `CiphertextBallotContest` and `CiphertextBallotSelection`.

children:
- `CiphertextSecretBallot` - (the current `CiphertextBallot`) which includes a required `nonce` and an optional `proof`
- `CiphertextVerifiableBallot` - no `nonce` and `proof` is required
- `CiphertextAcceptedBallot` - inherits `CiphertextVerifiableBallot` and includes the `state` field.

**Comment by keithrfung** [comment]
Will revisit in DTO conversations.
