### ISSUE TITLE
Implement Master Ballot Nonce Encryption

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-python#47]
there are several cases where we need to use a free-form encryption in the application.

1. when sharing keys between guardians
2. when storing or sharing nonce values
3. when encrypting/decrypting value in the `extended_data` field on a ballot

we will implement an "ordinary elgamal" encryption that will give us up to `3840` bits fo fidelity.

we will choose a prime p for ordinary ElGamal such that p mod 4 = 3, option 3 becomes easier in this case because it ensures that (-1) is a non-square mod p.

say we have a message `m`:

1.  append SHA-256(m) to get M=(m|SHA-256(m))
2.  Check if M is a square mod p by computing z = M^((p-1)/2) mod p
3. If z=1, compute an ElGamal encryption of M.  If z=-1, compute an ElGamal encryption of (-M) instead.

After decrypting, check if the final 256 bits is the SHA-256 hash of the first 3840 bits.  If it is, take the first 3840 bits as m.  If not, negate the result and then take the first 3840 bits as m (the remainder should match the SHA-256 hash of m).

## Design Considerations

sensitive values should be created and immediately encrypted in the same function where they are generated. They should only be long-lived in memory in the encrypted form.

open question: Should A guardian's election key pair should also be encrypted with the free-form encryption?

We must designate a fixed-length of the data that is going to be encrypt-able by the free-form encryption.  Given that secret keys are in the space [1,Q) it is likely we should choose 256 bits

Guardian keys:
1. election public/private key pair (for exponential elgamal)
2. election free-form public/private key pair (for ordinary elgamal, encrypting nonces, extended data, etc.)
3. secret-sharing public/private key pair (for any encryption scheme, our implementation is ordinary elgamal)

Election Keys:
1. election joint public key (exponential)
2. election joint free-form public key (ordinary)

### Generating the joint free-form key

The joint free form key is generated using the exact same secret sharing process as is used for the primary election key. 

### Sharing keys between guardians

When sharing keys between guardians, the free-form encryption is used to encrypt the election private key shares and the election free-form private key shares.  The function used to do this is pluggable to support an external system choosing to use a different form of encryption, such as RSA.  A stub for this already exists.  Our default implementation will re-use the same ordinary elgamal encryption mechanism we are using for the joint free-form key.  This means we will be using an ordinary elgamal key pair in the context of a guardian secret-sharing to encrypt another ordinary elgamal key pair used in the context of encrypting free-form values in the election

### Storing or sharing nonce values

Once the guardians have shared and verified the keys, a secondary election free-form joint public key is associated with the `CiphertextElectionContext` and used to encrypt the `random master nonce` values that are generated for each ballot.  The encrypted representation of the random master nonce replaces the current unencrypted nonce on the CiphertextBallot.

To support key flexibility, we must also support the use case that a specific consumer may not be using the guardian key ceremony artifacts and therefore we must allow a single public/private key pair to serve as the election joint free-form key.  This should work in a similar format to encrypting/decrypting ballots by using a single key that bypasses the key ceremony entirely.

This supports several use cases, specifically:
1. using the key ceremony for both encrypting ballots and nonce values, but separating the contexts with the 2 separate keys described above
2. using the key ceremony for encrypting ballot selections, but disallowing the guardians from decrypting or knowing the nonce values used for the ballots
3. similarly, using a single key pair for the ballots, but using the key ceremony for the nonces
4. using single values for the ballots and using single values for the nonces

### Encrypting/decrypting the value in ExtendedData

On a ballot, the extended data field is also encrypted with the election joint free-form public key.  In order to make the ballots homogenous, extendedData values are padded to max length.  if no data is passed in the extended data field, then random data is generated to fill the field.  There is more info in #35 

In the default workflow for an end-to-end election, the key ceremony guardians are used to generate both the joint public key and the free-form public key; and the free-form key is used to encrypt both nonces and extended data.  

In our implementation, if the key ceremony guardians are used for all keys, we only support reusing the free-form key for both extended data and nonces.  The option also exists to use a different free-form key for either the nonce values or the extended data fields by providing a single key-pair for either case. It is up to the consumer to implement this if desired.

**Comment by keithrfung** [comment]
This card is still blocked. 

The current thought is the default version of this will use a python package using AES encryption for performance. 
https://pypi.org/project/cryptography/ seems to be the optimal package with downloads in the millions. The encrypt/decrypt functions could still be overridden.

It is expected that a second set of public keys would be added into the key ceremony.

**Comment by JohnLCaron** [comment]
This change will affect the serialization formats.

**Comment by keithrfung** [comment]
@JohnLCaron Yes, it definitely will. However, we haven't firmly locked in yet for SDK 1.0. We are in the process of doing this. This being said, this will be rolled up into #508 . No need for two cards.
