### ISSUE TITLE
🚀  Use Milestone and Contributor information for Release Notes

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

ElectionGuard python uses GitHub milestones to keep track of all the issues. It would be very helpful to use these milestones to create the issues since closing milestones starts the release build. 

The idea is to use the title and description on the milestone to create the release description. 

As a fun addition, if we could display the contributors profile icons and links to their profiles on the release that would be an awesome way to showcase the communities contributions. 

### Possible Implementation

Here is an example of what the ideal release notes would look like:

```md
# Milestone Name
Insert milestone description

## Issues
[All included issues](link_to_milestone)

## Contributors
Display all contributors profile pictures and links to profiles
```

**Comment by wanjuntham** [comment]
Hello, may I take this up?

**Comment by wanjuntham** [comment]
> My thoughts would be to dynamically create the markdown document. I would likely make a command called `make release-notes` in the MakeFile. Then add items like:
> 
> ```shell
> touch release_notes.md
> echo '# Title` >> release_notes.md
> ```
> 
> We use https://github.com/actions/create-release to create the release. This file could probably be attached there.

@keithrfung Correct me if I am wrong, is it something like you want to have a `release_notes.md` in the root directory of this repo, and then each time a release build is created, the relevant changelog will be appended to the `release_notes.md`?
