### ISSUE TITLE
♻️.  Refactor ElectionPolynomial to use a Coefficient class

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Rehashing a card that @AddressXception made a while ago #84 . 

The `ElectionPolynomial` uses various types of lists, each of which is correlated to the others.  instead we should use a structure so that it is clear the values are mapped together.

This a polynomial and each of the lists will have the same amount of values since it is one value per coefficient.

Here's a code snippet of the existing code. 
https://github.com/microsoft/electionguard-python/blob/2bcd82b1289a079f55f8ef9bdaf5d6bd299d228a/src/electionguard/election_polynomial.py#L25-L41

### Possible Implementation

```py
SECRET_COEFFICIENT = ElementModQ  # Secret coefficient of election polynomial
PUBLIC_COMMITMENT = ElementModP  # Public commitment of election polynomial

@dataclass
class Coefficient: 
       value: SECRET_COEFFICIENT 
       """The secret coefficient `a_ij` """
       
       commitment: PUBLIC_COMMITMENT
       """The public key `K_ij` generated from secret coefficient"""

       proof: SchnoorProof
       """A proof of possession of the private key for the secret coefficient"""
```

```py
@dataclass
class ElectionPolynomial:
    """
    A polynomial defined by coefficients
    The 0-index coefficient is used for a secret key which can
    be discovered by a quorum of n guardians corresponding to n coefficients.
    """

    coefficients: List[Coefficient]
    """The coefficients of the polynomial"""
```

This will ripple through several methods.

**Comment by Brites101** [comment]
First timer here as part of hacktoberfest🍻. I want to try solving this issue.

 If i understood correctly, the proposed solution is to build a new dataclass to encompass the the coefficients. I will work on that!
