### ISSUE TITLE
🐞 Types cased like Constants

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are some types such as `GUARDIAN_ID` that are cased incorrectly. These variables function as types and not constants and therefore should be using "CapWords" since these are actually functioning as Type's. 

https://www.python.org/dev/peps/pep-0008/

### Expected Behavior

Global Constants should be capitalized with underscores
`THRESHOLD = 3` 

Classes and Types should be like this:
`GuardianId = str` 

### Environment

```markdown
- OS: Any
```

### Anything else?

It's probably helpful just to look at the types from this level for speed. 

https://github.com/microsoft/electionguard-python/blob/main/src/electionguard/__init__.py
https://github.com/microsoft/electionguard-python/blob/main/src/electionguard_tools/__init__.py
https://github.com/microsoft/electionguard-python/blob/main/src/electionguard_verify/__init__.py

**Comment by Meghwantsingh** [comment]
Hello , I would like to try this can I.

**Comment by keithrfung** [comment]
@Meghwantsingh You got it

**Comment by Meghwantsingh** [comment]
thx for assigning this problem sorry but I am currently working on some other project also so it may take some time or so sorry .
