### ISSUE TITLE
🔧  Fix DeprecationWarning on NotImplemented on ballot.py

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

`ballot.py` produces this warning when running `test_compact_submitted_ballot`. This issue is to resolve not ignore the warning.

```
=============================== warnings summary ===============================
tests/unit/test_ballot_compact.py::TestCompactBallot::test_compact_submitted_ballot
  /home/runner/work/electionguard-python/electionguard-python/src/electionguard/ballot.py:852: DeprecationWarning: NotImplemented should not be used in a boolean context
    isinstance(other, SubmittedBallot)
```

This can be seen when running `make test`

**Comment by sha016** [comment]
@keithrfung line 853 in ballot.py `super.__eq__(self, other)` evaluates to NotImplementedError, which explains the rest of error message (True AND NotImplemented AND True). I am not familiar enough with the codebase or its goals to suggest a change: it seems like the super class CiphertextBallot has implemented __eq__ for a reason (to check equality among different objects that share identical attributes?). If the __eq__ implementation is for test purposes only, I would suggest moving that logic outside the production code and into the unittest. I might need some guidance on what exactly is wanted here. Thanks!
