### ISSUE TITLE
🔐  Encrypt extended_data on contest and selection

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

On a ballot, both the contest and selection should have an `extended_data` field:
https://github.com/microsoft/electionguard-python/blob/37b55504b62c07cd6083ddcbebb8c6af84e574e6/src/electionguard/ballot.py#L74

On the selection this allows for data to be stored like write-ins for the contest this can help cover cases like issues like #385. This information should be encrypted using hashed elgamal.  

References issue #47 

### Possible Implementation

This card should include both adding the encryption, the field and ensuring that the encryption and decryption function

- [ ] Add extended_data field to Contest for Ballot
- [ ] Add decryption of extended_data for spoiled ballots
- [ ] Add tests
- [ ] Add documentation where necessary
- [ ] Replace ElgamalCiphertext with HashedElgamalCiphertext for extended_data fields

**Comment by keithrfung** [comment]
Marked as `question` because we are still waiting on the exact elgamal implementation for this.

**Comment by rc-ms** [comment]
[electionguard_aux_encrypt.pdf](https://github.com/microsoft/electionguard-python/files/8093416/electionguard_aux_encrypt.pdf)
