### ISSUE TITLE
🐞 hashing mod (q-1) should be mod q

### ISSUE THREAD

**Issue by danwallach** [microsoft/electionguard-python#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Today: hash.py is computing its result modulo `q-1`. This is an unusual choice but for the most part doesn't really matter, except when it does. With the HACL library, used in electionguard-cpp, the function `Hacl_Bignum256_mod()` has the constraint that it requires the modulus to be an odd number. `q` is odd. `q-1` is even.

The "obvious" solution here is to just replace `q-1` with `q`. This will have no meaningful impact on security or anything else, but will make implementations of ElectionGuard using HACL much easier to build correctly.

**Comment by keithrfung** [comment]
This seems like an overall good move. I wonder if **ElectionGuard 2.0** step.

**Comment by keithrfung** [comment]
This is the line being discussed:

https://github.com/microsoft/electionguard-python/blob/e35b68dc3175243ffaf872e9a0ea56c5b8a05830/src/electionguard/hash.py#L102-L104
