### ISSUE TITLE
🐞  For MacOS users, prefer python3 to python in MakeFile

### ISSUE THREAD

**Issue by ramsdell** [microsoft/electionguard-python#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On MacOS, the install and build scripts use `python` command which for MacOS without configuration is Python 2.7.

### Expected Behavior

The scripts should reference Python3 which can be done by using `python3` uniformly.

### Environment

```markdown
- OS: MacOS 11.6.2
```

### Resolution

Replace all `python` commands with `python3` in MakeFile

https://github.com/microsoft/electionguard-python/blob/a4d6cb43cb1573e19c52d4560d06fa38ecfe59ee/Makefile#L4
https://github.com/microsoft/electionguard-python/blob/a4d6cb43cb1573e19c52d4560d06fa38ecfe59ee/Makefile#L6
https://github.com/microsoft/electionguard-python/blob/a4d6cb43cb1573e19c52d4560d06fa38ecfe59ee/Makefile#L8
https://github.com/microsoft/electionguard-python/blob/a4d6cb43cb1573e19c52d4560d06fa38ecfe59ee/Makefile#L17
https://github.com/microsoft/electionguard-python/blob/a4d6cb43cb1573e19c52d4560d06fa38ecfe59ee/Makefile#L114

**Comment by rc-ms** [comment]
Hello @ramsdell thank you for your submission. mac and python fills me with sighs. we have had dependencies that have pushed us across and then back again this awkward divide. as we solidify the final 1.0 ElectionGuard Spec (which will be tied to the next Python release) we should have a definitive, consistent implementation, ideally python3. the dev team is stepping back for a couple of weeks but expect this to resolve soon

**Comment by keithrfung** [comment]
1. On MacOS, this is true if the python version is not replaced. For example, this is not true on my MacOS setup. It just depends on the individuals setup. 

Example:
![Screen Shot 2022-01-24 at 11 33 18 AM](https://user-images.githubusercontent.com/10125297/150824251-0184f8ca-f316-430f-965a-8f755d4d5f64.png)

2. AFAIK many of the commands that are run don't have a need to force python 3 vs 2. 

These things being said, this issue would be a question of consistency of experience across operating systems. Choosing to use `python3` for all the commands in the MakeFile would make the experience consistent and simpler and that should be our goal. I will update the issue a bit to reflect this.
