### ISSUE TITLE
✨The Guardian ids should be added to the coefficients JSON file

### ISSUE THREAD

**Issue by JohnLCaron** [microsoft/electionguard-python#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Currently the lagrange coefficients are simply serialized as a list:
```
{
    "coefficients": [
        "05",
        "FFE7",
        "0A",
        "FFEC",
        "01"
    ]
}
```

Which Guardian do they reference? One could assume that one can read the GuardianRecords and sort them (on sequence_order?) and match them up.

However, what happens when the number of decrypting guardians is not the full number? Should only the "available" GuardianRecords be saved into the election record? This is not described anywhere, AFAIK. And the library itself does not enforce any such usage. One could imagine that the GuardianRecords might be conveniently stored during the KeyCeremony. Only during decryption do you know which are available for decrypting. Only when you know the set of  available Guardians can you compute the lagrange coefficients .

Seems more robust to store the guardian ids with the lagrange coordinates. This would also unambiguously specify which guardians were part of the decryption.

### Possible Implementation
```

@dataclass
class LagrangeCoefficientsRecord:
    coefficients: List[ElementModQ]
    guardian_ids: List[str]
```

### Anything else?

Not sure if there are any python tests for the case when all guardians are not used for decryption. TestEndToEndElection seems to only have the full case? Would be good to generate a canonical test election record for both full and not full case, so verifiers can test their code.

**Comment by JohnLCaron** [comment]
Turns out we need the GuardianRecords to be the full set, since validation 3.b requires us to validate the Election Public-Key, which requires the public keys from all the guardians.

So I dont see any alternative to adding the guardian_ids to the LagrangeCoefficientsRecord. Ive been using the name AvailableGuardians for this class.

**Comment by rc-ms** [comment]
We are doing work on the public election record, which is where this data structure would manifest, and is actively being being worked on right now. The point is well taken and would make writing verifiers simpler. I will surface this with the team to discuss. @benaloh do you have any thoughts?

**Comment by JohnLCaron** [comment]
I dont see where in the current JSON serialization you specify which guardians were used during decryption. (I may be missing something obvious.)

The lagrange coefficients depend on knowing what guardians are used; so impossible to verify without knowing that.

**Comment by keithrfung** [comment]
I agree. The LaGrange Coefficients are determined at decryption time so this needs to be resolved prior to SDK 1.0 being released and should be included in those serialization changes. 

Marking as `question` because we need to determine exactly what to identify the guardian used. Long term, I believe we should reconsider how we export the guardian info or maybe the aggregated ballot / tally to include this. This being said, the other question is id of the guardian vs the sequence_order of the guardian. 

This ends up almost being an attendance of the decryption of sorts. Later on maybe we should treat it as such.

**Comment by keithrfung** [comment]
We're gonna move forward on this. I believe for now, `guardian_id` and `sequence_order` might both be good additions to this to allow the correct ordering but also help identify the guardians.

**Comment by JohnLCaron** [comment]
sounds good
