### ISSUE TITLE
🐞 Schnorr challenge incorrectly calculated

### ISSUE THREAD

**Issue by ramsdell** [microsoft/electionguard-python#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On Line 50 of schnorr.py, it calculates the challenge as:

c_ij = H(K_ij, h_ij)

But the spec in Section 2, Eq. A, on Page 26 states the correct challenge is:

c_ij = H(Q, K_ij, h_ij)

### Expected Behavior

The challenge should be:

c_ij = H(Q, K_ij, h_ij)

### Environment

```markdown
- OS: MacOS 12.2
```

**Comment by JohnLCaron** [comment]
See issue and discussion #278

**Comment by keithrfung** [comment]
@JohnLCaron Thanks! Will close this. I forgot how we handled this.
