### ISSUE TITLE
✨ Boolean fields should be serialized as "true" or "false"

### ISSUE THREAD

**Issue by JohnLCaron** [microsoft/electionguard-python#532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

boolean values are encoded sometimes as "00" or "01" or null or true or false. 
- where the field is bool, eg CiphertextBallotSelection.is_placeholder_selection, it is encoded as "00" or "01".
- where the field is Optional[bool] , eg Manifest.Candidate.is_write_in, is encoded as null or true or false.

### Expected Behavior

Recommend true or false for clarity.

Recommend not using Optional for boolean fields to be serialized, or encode null as false.

### Environment

```markdown
- OS:
```

### Anything else?

A boolean field should not be encoded as a number (eg 0 or 1 votes) in the serialized format. It could be converted to a number in an internal implementation class if needed.

**Comment by keithrfung** [comment]
Over explanation for clarity of other developers. 

There are cases where fields that may seem boolean are integers. Vote is the best example. `vote` is intentionally an int as `0` or `1` . This is ideal for creating an AggregateBallot where `vote` or `tally` is a number above `1`. This however should not be true for actual `bool` fields. 
https://github.com/microsoft/electionguard-python/blob/e35b68dc3175243ffaf872e9a0ea56c5b8a05830/src/electionguard/ballot.py#L68

This issue focuses on a version of the CiphertextBallot that is no longer accurate. See this reference to updated data. These should always serialize as `true` or `false` from here on out. 
https://github.com/microsoft/electionguard/blob/24dea6805bc2485566f1519280e1abb90a45ead5/data/0.95.0/sample/full/election_private_data/ciphertext_ballots/ciphertext_ballot_ballot-06e7aa04-73fc-11ec-8051-acde48001122.json#L35

The sample data for reference will from now on be in `electionguard` to avoid the python and c++ repositories.  Issues such as this should be in that repository. 

------------------------

All this being said, the concern for removing usages of `Optional[bool]` is still relevant to reduce confusion. Marking this as **question**, so we can determine which fields are `Optional[bool]` that we can change to `bool` that are serialized serialization? @JohnLCaron feel free to mention the areas you're concerned with.

**Comment by keithrfung** [comment]
See alternate issue.
