### ISSUE TITLE
Consistent Multiprocessing for Tally

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-python#54]
multiprocessing is used in a few places to speed up computation of some large values.  When using the library in the recommended way, it behaves as expected, however it is possible to deadlock by calling internal functions.  This is illustrated by `Pool` objects existing in multiple scopes.

Proposed solution:

Implement a consistent queuing strategy for scheduling work on multiple processors so that the library cannot be deadlocked intentionally or unintentionally.

The focus on this card is going to be moved to displaying an example of paralleling for Tallies specifically.

**Comment by keithrfung** [comment]
The concept for this is that Pool is currently used in many places and to make a situation where there is only one use of this. For example, `scheduler.py` or `worker.py` that would instantiate a global pool instead of reinstantiating it every time. This would allow others to override this class in the future.

**Comment by danwallach** [comment]
FWIW, I'm currently investigating Ray (https://ray.io/) and PySpark (https://spark.apache.org/examples.html) for `arlo-e2e`. I haven't decided on exactly which way we're going to go.

Meanwhile, you may want to look at how I did tallying (https://github.com/votingworks/arlo-e2e/blob/main/src/arlo_e2e/tally.py). Every relevant function takes an `Optional[Pool]` argument. If it's not there, it just does a list comprehension. If it is there, it uses that pool to do the parallel map. This pushes the pool _creation_ out of all the libraries to whoever is starting the computation.
