### ISSUE TITLE
🐞 Deserializing SubmittedBallot makes ElgamalCiphertext comparison fail

### ISSUE THREAD

**Issue by thommignot** [microsoft/electionguard-python#547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since the new serialization has been merged, deserialization fails to reconstruct `SubmittedBallot`s

I'm trying to write the `SubmittedBallot`s to file. In order to create the tally, I deserialize the ballots with the `electionguard.serializer:from_file` function.
By doing this, the `ElgamalCiphertext` aka `ciphertext_accumulation` becomes different from the result of `elgamal_accumulate` function thus result in an invalid ballot that does not become part of the tally.

the `ciphertext_accumulation` is of type `__Pydantic_xxxxxxxx_ElgamalCiphertext` and there's no `__eq__` that can handle this by default.

I see there are some `__eq__` functions defined in electionguard-python and they are all like:
```python
def __eq__(self, other):
    return (
        isinstance(other, type)
        and self.x == other.x
        and self.y == other.y
        ...
    )
```

which is the default `__eq__` function that pydantic generates for `dataclasses`

I suggest that all `dataclasses.dataclass` could be replaced by `pydantic.dataclasses.dataclass`

Pydantic handles the builtins `dataclass.field` with the same syntax and that would allow a working deserializing and generate the `__eq__` function so we could remove them.

If not, we can add only the `__eq__` function for the `ElgamalCiphertext` class, that would help in my own case but I'm not sure that it would be very nice to help such a specific use case.

What could I, in my case, if case dataclasses are not replaced, to deserialize my ballots except by recursively deserializing every class involved in such a ballot ?
What would be the point in being able to serialize every single object in electionguard if deserialization don't work as one could expect?

That's why I think electionguard should use pydantic from start to end, not partly.

### Steps To Reproduce

use the `electionguard.serialize:to_file` to write a `SubmittedBallot`
use the `electionguard.serialize:from_file` to load a `SubmittedBallot`

compare the ballot's `ciphertext_accumulation` with the result of its `elgamal_accumulate()` method

### Environment

```markdown
- OS:
```

**Comment by keithrfung** [comment]
@thommignot Strong case and followup. Will look into. I'm inclined to agree. Pydantic is supposed to work with dataclasses but I think our issue is the override specifically on the `__eq__` function.

**Comment by keithrfung** [comment]
Possible solution: ♻️ Refactor dataclasses to rely exclusively on pydantic dataclasses

Removes requirement of equal methods throughout code base since default methods should suffice. This could create problems around sections that use `fields` or `post_inits` that do not perfectly reconstruct.

The `__eq__` method could then be removed in favor of the built in ones in pydantic dataclasses to reduce redundancy and overall code size.

**Comment by keithrfung** [comment]
As relevant data and tests, we do have a test that includes specifically a test for deserializing.
https://github.com/microsoft/electionguard-python/blob/2a903e405f167e19e76664f69153c3532ee7b9d9/tests/integration/test_end_to_end_election.py#L582-591

**Comment by thommignot** [comment]
Just clarifying a mistake of mine:

It's all about a `CiphertextBallotContest` in `SubmittedBallot`'s `contests`

```python
from electionguard.ballot import SubmittedBallot
from electionguard.serialize import from_file

ballot_path = "path/of/a/ballot/file.json"
ballot = from_file(SubmittedBallot, ballot_path)

contest = ballot.contests[0]

assert contest.ciphertext_accumulation == contest.elgamal_accumulate()
```
raises `AssertionError`

We should add a test for the ballot's `is_valid_encryption()` method, something like:

`tests/integration/test_end_to_end_election.py:`
```python
591             self.assertTrue(
592                 ballot_from_file.is_valid_encryption(
593                     self.internal_manifest.manifest_hash,
594                     self.context.elgamal_public_key,
595                     self.context.crypto_extended_base_hash
596                 )
597             )
```

But I'm not sure it would be the right place to put such a test.

**Comment by keithrfung** [comment]
For the record, I took a swing at switching everything to pydantic, this is not something we can do at this time without significant changes to the model structure. I think that type of work may have to shift to 2.0. Particularly because a few of the "data" classes or DTO's use `Protocol` . Understandably, these conflict pretty significantly.

**Comment by thommignot** [comment]
> For the record, I took a swing at switching everything to pydantic, this is not something we can do at this time without significant changes to the model structure. I think that type of work may have to shift to 2.0. Particularly because a few of the "data" classes or DTO's use `Protocol` . Understandably, these conflict pretty significantly.

Bad luck, because not using `pydantic.dataclasses.dataclass` instead of `dataclasses.dataclass` make pickle throw an error in `CiphertextTally._execute_accumulate()`

it raises:
```
_pickle.PicklingError: Can't pickle <class 'pydantic.dataclasses._Pydantic_ElGamalCiphertext_94561651352912'>: it's not the same object as pydantic.dataclasses._Pydantic_ElGamalCiphertext_94561651352912
```

This does not occurs with the `pydantic.dataclasses.dataclass` decorator on `class ElgamalCiphertext`

maybe related to this issue: https://github.com/samuelcolvin/pydantic/issues/2111

I don't know if I should create another issue for electionguard-python, I ended up writing a store that pickles the ballots directly.
