### ISSUE TITLE
Improve metadata validation

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-python#55]
The current implementation of input validation for an ElectionDescription skips a few details:

- there is no verification on `ElectionType`.  for instance, for party primaries, then all candidates should have the same party?
- there is currently no validation done for ballot styles connected to party id's and verifying the contests are correct for that style
- we should require that every candidate has a party specified, and that there is a special party for `non-partisan`
- we should verify that the contest sequence order set is in the proper order for the election
- document and validate the candidate_id in SelectionDescription

**Comment by keithrfung** [comment]
https://github.com/microsoft/electionguard-python/discussions/286
