### ISSUE TITLE
✨ Add extended_data field to Contest

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

The contests on a ballot need an extended_data field to store information particularly for the overvotes use case. This data as detailed in #385 can be used to store information that the contest was overvoted. This is only to add the fields and segment some of the work out and should be accessible for coders starting out with ElectionGuard.

### Possible Implementation

The existing implementation from the ballot selections should be able to be replicated for contest

Example from `PlaintextBallotSelection`
https://github.com/microsoft/electionguard-python/blob/c59fddcd89f85619ba801d6c38b1ea7f08210951/src/electionguard/ballot.py#L74-L77

Example from `CiphertextBallotSelection`
https://github.com/microsoft/electionguard-python/blob/c59fddcd89f85619ba801d6c38b1ea7f08210951/src/electionguard/ballot.py#L176-L177

These should be added to the similarly named
`PlaintextBallotContest` and `CiphertextBallotContest`

**Comment by heysujal** [comment]
Hey I would like to work on this issue . Can you guide me?
