### ISSUE TITLE
📄 Change ElectionConstants big integers to store as hex

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Referencing issue #524, this is a quick solution to resolve that issue with minimal changes while we should revisit this as a whole in ElectionGuard 2.0.

### Possible Implementation

The `ElectionConstants` dataclass does not `ElementModP` and `ElementModQ` but instead int so these items serialize into integers. This can't be quickly solved by changing the types because the `ElementModP` and `ElementModQ` currently use this class to handle the modulus limits. 

Here is the Election Constants class
https://github.com/microsoft/electionguard-python/blob/c59fddcd89f85619ba801d6c38b1ea7f08210951/src/electionguard/constants.py#L8-L22

This is the fastest solution to resolve this problem that can also help highlight the differences in python as other languages. Create a `BigInteger` class that `BaseElement` inherits from. This class could be in a separate file called `.biginteger` that `ElementModQ` could inherit from then all the integers used in ElectionConstants could use this. 

```py
p: BigInteger
q: BigInteger
r: BigInteger
g: BigInteger
```

**Comment by colleenirt** [comment]
Keith take this once done with current cards?
