### ISSUE TITLE
Support regenerating and reverifying tracking codes

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-python#57]
Tracking codes are generated based on a specific ballot marking device.  In order to verify that the tracking codes are constructed correctly, each ballot has to be associated with the device that encrypted it.

in `encrypt.py` add the `device hash` to the `encrypt_ballot` function interface so it can be propagated with the ballot. Also propagate the `seed hash` so that the ballot tracking id's can be regenerated by traversing the collection of ballots encrypted by a specific device.

**Comment by keithrfung** [comment]
https://github.com/microsoft/electionguard-python/discussions/282
