### ISSUE TITLE
🐞  Include electionguard_tools in package

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The electionguard_tools should be included within the package since electionguard_cli depends on them. 

### Expected Behavior

Add electionguard_tools to this section
https://github.com/microsoft/electionguard-python/blob/8aa589c9744bdf52e1e2659e2f83c255ffc65441/pyproject.toml#L23-L27

Ensure `pylint` and `mypy` are also checking electionguard_tools

### Environment

```markdown
- OS:
```

**Comment by MatthewRatzell** [comment]
I'm working on this at the moment I'm currently in the process of fixing the lint errors in tools because I am unsure if that would break your CI and I don't want that to happen so I'm making sure all errors are handled before sending fix upstream

**Comment by keithrfung** [comment]
@MatthewRatzell It would break issues upstream.

**Comment by MatthewRatzell** [comment]
Just wanted to give a heads up I'm still working on this I've been super busy with some uni projects, but I haven't forgotten about this

**Comment by keithrfung** [comment]
Outdated by #647

**Comment by keithrfung** [comment]
Reopened to ensure package properly builds until #647  is complete.
