### ISSUE TITLE
🐞  Remove unnecessary Key Ceremony Steps

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In this section of code, the full ceremony is already performed before a second set of rounds is done. This isn't required. 
https://github.com/microsoft/electionguard-python/blob/03698c683ab35f608e35dc9b66217caa1d40f7eb/src/electionguard_cli/e2e_steps/key_ceremony_step.py#L24-L30

### Expected Behavior

Only the `perform_full_ceremony` should be necessary. The other steps can be removed. 

### Environment

```markdown
- OS:
```

**Comment by phershbe** [comment]
I can do this if you would like. I'm trying to understand the code base more so that I can contribute to more in the future here. Let me know!

**Comment by keithrfung** [comment]
@phershbe Have at it! This is a good starting point. 

Be sure to look at how the poetry commands work but this is hooked up to one of the make commands

**Comment by lprichar** [comment]
Sorry @phershbe, I hope you haven't made much progress, I implemented this in https://app.zenhub.com/workspaces/electionguard-61f3025a55391f00182524ed/issues/microsoft/electionguard-python/613 without realizing I was stepping on toes

**Comment by phershbe** [comment]
@Iprichar No problem, I had not started yet because I was still working on my previous PR here. Thank you for letting me know!
