### ISSUE TITLE
installation-steps for beginners

### ISSUE THREAD

**Issue by MellowVoidUser** [microsoft/electionguard-python#61]
Hi, I would like to suggest to put more detailed steps about howto install and start using everything in the readme file. Executing make or sudo make isn't working for me. Could be something todo with different versions of python on my system and me not having basic knowledge about this. (I'm on Linux mint) but I guess I wont be the only beginner who will bump onto this.

**Comment by keithrfung** [comment]
Can you provide more details on exactly what isn't working or what you're struggling with? We are actively keeping the documentation concise at the top level so we're looking for exactly the details that would assist.

**Python Version**
This implementation runs off a specific version of python (3.8) which is mentioned in the [requirements](https://github.com/microsoft/electionguard-python#-requirements). 
You can check this in your local directory with `python --version`. If you have multiple versions, I can suggest [pyenv](https://realpython.com/intro-to-pyenv/) to help manage them.

**MakeFile**
The `make` file has a bit more of a breakdown in the [Build and Run section](https://github.com/microsoft/electionguard-python/blob/main/docs/Build_And_Run.md) which is linked in the ReadMe.

**Comment by MellowVoidUser** [comment]
The link to pyenv you provide seems usefull but I'm getting completely screwd up by it, I just can't get pyenv to install a python version. (for instance pyenv install -v 3.8.1 gives this  error:

(OK):download completed.
Parent is shutting down, bye...
tar (child): Python-3.8.1.tar.xz: Functie open() is mislukt: Bestand of map bestaat niet
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/home/victor/.pyenv/plugins/python-build/bin/python-build: regel 238: pushd: Python-3.8.1: Bestand of map bestaat niet
BUILD FAILED (LinuxMint 19.3 using python-build 20180424)

maybe I should try a clean install..

**Comment by keithrfung** [comment]
It seems like a clean install is the correct answer. The error you have looks specific to python installation. 

I'm going to add a pull request to add some details and ensure future users are aware of the requirement of python 3.8 and link to installation of pyenv. Then I'll close this issue.
