### ISSUE TITLE
⚡️ Generate Plaintext Ballots in CLI

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Generate plaintext ballots with a given manifest to CLI. `PlaintextBallot` should be generated with a random set of data from the `Manifest` according to valid `ballot_styles` from the Manifest. 

### Possible Implementation

The CLI should take a particular number of ballots to create and a dedicated `ballot_style` as a string to allow creating a specific style. 

Marking a ballot is the term for creating a plaintext ballot so a command like so makes sense. 

Example: 
```bash
eg mark-ballots 100 "ballot-style-1"
```

### Anything else?

This should take advantage of the already existing `BallotFactory`. 
It would be wise to boyscout this file where required. 
https://github.com/microsoft/electionguard-python/blob/main/src/electionguard_tools/factories/ballot_factory.py

As a heads up, information about `@composite` can be seen here: 
https://hypothesis.readthedocs.io/en/latest/data.html

**Comment by phershbe** [comment]
@keithrfung I'm interested in working on this, but I'm in a little bit over my head on this issue. I'm digging through the code to try to understand some parts better such as the CLI, the manifest, and the ballot_factory, as well as how the factory design pattern works. If you or anybody else had a few minutes to explain some of the code to me, hopefully I could repay you by solving more issues in the future, don't feel obligated though, if not I'm going to keep digging to understand the code better.

**Comment by lprichar** [comment]
@phershbe that sounds like an excellent deal.  This ticket has enough independence it'd be a good ticket and extremely helpful. 
 However, the manifest can definitely be a bit intimidating.  What questions did you have?  Are you able to get the CLI up and running with e.g. the e2e command?

**Comment by phershbe** [comment]
@lprichar I'm totally self-taught and haven't worked as a software engineer yet, so this is a bit overwhelming, I'm learning a lot and not giving up though. I already knew how to do the quick start with make, and after some digging I now can use 'poetry run eg e2e' in the main directory. That is the CLI, yeah? That's where I'm at now, I'm going to spend a few more hours tonight and tomorrow and figure out what I can about this issue and come back with more questions.

**Comment by phershbe** [comment]
@lprichar Here are the questions that I have so far:
1. Is the "eg" in **eg = 'electionguard_cli.start:cli'** in pyproject.toml the same “eg” used for **poetry run eg e2e** in Makefile?
2. Will the **eg mark-ballots 100 "ballot-style-1”** suggested in the issue above go in the Makefile?
I'm doing tutorials to better understand **click**, **toml**, and **Makefile**.
Yes, I did get the CLI up and running I'm pretty sure.
Any answers and direction that you can provide quickly would be awesome; even you mentioning getting the e2e command up and running for the CLI in your previous comment was helpful for me understanding where to start.

**Comment by phershbe** [comment]
@lprichar @keithrfung I'm going through the project and learning a lot about object-oriented programming, the decorators that are being used, the CLI, how the factories work, Poetry, the Makefile, tests, the manifest,  and more. I'm trying to get it by myself, and I'm learning a lot, but it's taking a while to put the pieces together. With some help I can definitely get it or maybe I'll get it myself soon too, but I'm here to help the project, so if it's easier for somebody in charge to do or something, feel free, and I can study the changes after. Thank you!!
