### ISSUE TITLE
object_ids should have internal structure

### ISSUE THREAD

**Issue by danwallach** [microsoft/electionguard-python#68]
Right now, these `object_id` strings are tricky. Since they’ve all got the same type (string), it’s easy to mix them up.

Proposal: all `object_id` strings should have a “type prefix” (think: “Hungarian notation”), which is enforced by all the constructors for ElectionGuard core types. So, for example, all `Candidate` `object_id`s must start with the prefix “candidate” and then can be anything after that, so `candidate1`, `candidate2`, or `candidate-0195-ab3f-129b`, doesn’t matter, so long as you’ve got the right prefix.

Then, when you’ve got cross-references, where one thing names another, you can “type check” the `object_id`s to make sure they’ve got the proper prefix.

Example: a `BallotStyle` has a list of `GeopoliticalUnit` `object_id`s in it. If the `BallotStyle` constructor required every string in that list to have the prefix `gpunit`, that would catch bugs and be useful during debugging.

**Comment by keithrfung** [comment]
https://github.com/microsoft/electionguard-python/discussions/287
