### ISSUE TITLE
GeopoliticalUnit vs. BallotStyle, and what to do if the former is absent

### ISSUE THREAD

**Issue by danwallach** [microsoft/electionguard-python#70]
Consider the case of ElectionGuard being used to encrypted a manifest of ballots from a list of CVRs, where we know (or can infer) the ballot styles, but where we have no information about the geopolitical units. 

At that point, any attempt to infer GeopoliticalUnits will need to wing it. The choices seem to be:
- GeopoliticalUnits map one-to-one with contests
- GeopoliticalUnits map one-to-one with ballot styles
- You have one singular GeopolitcalUnit and use that everywhere

What's a GeopoliticalUnit *supposed* to be? That's a bit unclear, but a useful way to think about it is a polygon on a map. 

The singular GeopoliticalUnit seems like the preferable solution, as opposed to just making things up. Consider some problems with the other options:

- A Contest, by definition, has a singular `electoral_district_id`, which is meant to be a GeopoliticalUnit. Since a Contest can appear across multiple ballot styles, this means the "one-to-one with ballot styles" option doesn't work.
- So what about one-to-one with contests? This *could* work, and makes the GeopoliticalUnit data into a shadow copy of the Contest data. At that point, it's reasonable to ask why we're tracking GeopoliticalUnits at all.

**Performance implications**

(Need to double check this, but...) Right now, when ElectionGuard encrypts ballots, the work it does is apparently based on the GeopoliticalUnits rather than on the BallotStyles, in terms of not bothering to encrypt choices that a voter wasn't presented on any given ballot. This means that a singular GeopoliticalUnit would have slower encryption performance than a GeopoliticalUnit one-to-one with Contests.

Arguably, the BallotStyle data should be definitive in what Contests are and are not encrypted on any given ballot.

**Comment by keithrfung** [comment]
This relates to the various vote variation possibilities.
https://github.com/microsoft/electionguard-python/discussions/283
