### ISSUE TITLE
🐞 In the CLI, the ballot generation has an issue with the pick 2 or 3 ballots

### ISSUE THREAD

**Issue by SteveMaier-IRT** [microsoft/electionguard-python#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current plain text ballot generation will make ballots for a manifest, if there are contests with the number_elected set to 2 or 3, then there might not be 2 or 3 selections picked in the ballot generated.  The generation process needs to be able to vote for the number that is in the manifest.  

### Expected Behavior

Have the number selected in the plain text ballot be the same as the number_elected for most of not all of the ballots.

### Environment

```markdown
- OS:
```

**Comment by shreyasminocha** [comment]
Sure, I'll look into it
