### ISSUE TITLE
Remove BallotStore

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-python#74]
The ballot store is deprecated in favor of using the generic DataStore.  this ticket is to remove the ballot store and replace all usages with a generic data store

**Comment by jacobggman** [comment]
Can I do that?

**Comment by jacobggman** [comment]
Basically every `BallotStore` replace with `DataStore`?

**Comment by keithrfung** [comment]
@jacobggman Yes. Simple as that afaik. We're just trying to remove the dependency on a Ballot specific implementation.

**Comment by shivamdn9** [comment]
Hi @keithrfung ,if jacob not working on this issuee,i would like to.
