### ISSUE TITLE
🐞 Multiple ballot uploads should tally together

### ISSUE THREAD

**Issue by SteveMaier-IRT** [microsoft/electionguard-python#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the event multiple EGDrives are uploaded to EG Admin the tallies for each EGDrive are not combined into one tally

**Scenario:** 
1.	Demo Scan is in use for a few hours
2.	A hardware failure occurs and this scan goes down
3.	A backup Scan is brought into service and finishes out the Election Day Pilot
4.	I now have 2 EGDrives to upload to EG Admin

**Setup:** 
1.	Upload the EGDrive from Scan 1 and decrypt
2.	Upload the EGDrive from Scan 2 and decrypt
3.	Verify the resulting tally on EG Admin

**Expected Result:**
1.	I should be able to view the tally on EG Admin that is a combined total from both EGDrives

**Actual Result:**
1.	There a separate tally for each uploaded EGDrive.  The tallies are not combined
Impact: Low - Scenario will only be seen if the loading of multiple EGDrives is needed (such as in the event of a hardware failure in Scan) 

**Defect Details**
Defect 15949
Reproducible	Y
Severity	1-Low
Detected on Date	2022-08-18
Defect Type	Product Defect
Modified	2022-08-18 14:38:29
Detected in Release	ElectionGuard
Detected in Cycle	Drop 4

### Expected Behavior

I should be able to view the tally on EG Admin that is a combined total from both EGDrives

### Environment

```markdown
- OS:
```

**Comment by SteveMaier-IRT** [comment]
Tested this and could only reproduce any type of issue if the same ballots were scanned on that second device.  With the same ballots, those were detected as duplicates during the tally and not counted twice.  When a new ballot was added it, a new tally showed a new number.

**Comment by colleenirt** [comment]
which ballots were duplicates and what specifically about the ballot was duplicated?
