### ISSUE TITLE
Add crypto "test parameters" to speed up unit tests

### ISSUE THREAD

**Issue by danwallach** [microsoft/electionguard-python#76]
**The problem**: Big unit tests suites run slowly, bottlenecking on the cryptographic computations.

**The current workaround**: Reducing the number of tests or the size of the tests that run. Particularly for the Hypothesis tests, this reduces their ability to find bugs.

**The better solution**: Have smaller values for `P`, `Q`, and `G`, such that everything fits in 32 bits or even 16 bits. 

**The challenge**: How do we introduce "test parameters" without them ever, ever finding their way into production code? What's the minimal set of changes to add a "test mode"?

Two broad options:
1) "Monkey patching" or otherwise having test code, from outside of the `electionguard` package, reach into the package and make changes. Editing the values of `P`, `Q`, and `G` is easy. Similarly, it looks like all you have to do is change `Q_MINUS_ONE` and you'll fix `hash_elems`.
2) Having a "test mode switch" wired directly into the `electionguard` package. It sets a globally visible boolean flag and overwrites the values of `P`, `Q`, `G`, etc. It would also nuke the `dlog` cache state.

I'm slightly in favor of the "test mode", since it can generate suitably loud warnings if it's ever used in a real election, or could even disable specific features, like writing persistent data to a file. Another way to ensure mistakes aren't made is to just write out the parameters as part of any election file, so if we see any election with "test parameters", that will be an instant read flag. Like, trying to load up some persistent data, the first thing you do is check the parameters, and if they're not equal to what you expect, you raise an error.

**How do you pick the right parameters?** Says our resident cryptographer: "All we need is any small prime q that is larger than the number of voters and a larger prime p such that p-1 is a multiple of q.  We don’t have to go to all of the trouble I did to select primes to optimize other characteristics and to do so in a publicly-justifiable way."

I already had a Sieve of Eratosthenes program hanging around, so I searched for the smallest `Q` greater than 32767 (2^15 - 1) and came up with:
```
P = 65543
Q = 32771
```

**Comment by danwallach** [comment]
I'm playing with this from external code, and one issue is that P and Q are final, so assignments to them are "not allowed" (to the extent that anything in Python is not allowed).

**Comment by danwallach** [comment]
Update: as an experiment, I just put these small constants into `group.py` and tried running the unit test suite. I tried G=4 (what you get by default) and G=2 (Josh had suggested). They yielded different tests failing.

Further examination of this led me to discover one bug in test_elgamal.py:
```
# starts at line 87
    @given(elgamal_keypairs())
    def test_elgamal_generated_keypairs_are_within_range(self, keypair: ElGamalKeyPair):
        self.assertLess(keypair.public_key.to_int(), P)
        self.assertLess(keypair.secret_key.to_int(), G)
        self.assertEqual(g_pow_p(keypair.secret_key), keypair.public_key)
```
That `G` should be `Q`. 

So, one bug down, several left to go. Suffice to say that this issue is now a bit more than just making the tests run faster. It's also apparently a useful way of discovering bugs in the tests and/or the main code itself.

**Comment by rc-ms** [comment]
We're going to do this work when we change the base primes, which is right now slated for post June 30th, but high on the early deliverable list

**Comment by AddressXception** [comment]
linking to #329 so that this gets addressed then
