### ISSUE TITLE
Create a Base Verifier for Election

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#78]
Create a base verifier to test results output by python repo to demonstrate to new users how to verify elections.
Expectations are a `verify.py` in the `/src` and an individual test (`test_verify.py`) as well as additions to the integration test.

This will be a basic verifier and will draw from information provided by:
- Josh Benaloh
- Existing v0.85 spec
- Rust Verifier 

This should also include a final step of documentation added on to the docs. This would be `5_Publish_And_Verify.md` detailing the steps of publishing information and then allowing others to verify.

--------

Update: 
The likelihood is that this really should really be broken up by what it is verifying. This could lead to this being more like a separate package that relies on the existing `electionguard` python package and builds on it. 

`electionguard-verifier` or something like this.

**Comment by keithrfung** [comment]
https://github.com/microsoft/electionguard/issues/32

Based on this, a base verifier would include at minimum a ballot and tally verifier. A test for this could consume some of the test data. 

This would likely include a unit test similar to some of the others in the repository and integration into the end to end test.

**Comment by nguyenquannnn** [comment]
Hi Keith, would love to take a dig at this for hacktoberfest!

**Comment by keithrfung** [comment]
Closed in favor of new tasks.
