### ISSUE TITLE
"Pluggable parallelism"

### ISSUE THREAD

**Issue by danwallach** [microsoft/electionguard-python#85]
Right now, ElectionGuard-Python is using Python's `multiprocessing.Pool` library to execute in parallel on multicore machines. It works great.

But, it's likely that somebody will want to run much bigger jobs (e.g., "encrypt a million ballots"), for which no single computer has the necessary horsepower. Turns out, there are lots of libraries that do almost all the hard lifting. For example, *Ray* claims to be able to be [one-line code change for this](https://medium.com/distributed-computing-with-ray/how-to-scale-python-multiprocessing-to-a-cluster-with-one-line-of-code-d19f242f60ff). 

ElectionGuard-Python shouldn't necessarily pick favorites, nor should it necessarily carry these cluster libraries around as dependencies. Instead, the seemingly right solution is to have "pluggable parallelism", where ElectionGuard-Python uses a very narrow API that can be easily implemented by building modest wrappers around Ray or other such tools.

**Comment by keithrfung** [comment]
https://github.com/microsoft/electionguard-python/discussions/274
