### ISSUE TITLE
Remove _is_protocol_ from results output

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#94]
`_is_protocol_` a private variable is present on the results output. This should be removed as it seems to be a result of an output setting that is unnecessary. Should be simply removed from the `serializable.py`

**Comment by karl01101101** [comment]
Does adding `_is_protocol_` to the `KEYS_TO_REMOVE` array of `serializable.py` do that or are changes to `strip_privates` required at all? I've tried doing the first change and then running the test through WSL but I'm not sure where to check for the output to confirm it's been removed.
