### ISSUE TITLE
Publish Ballot Manifest

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#96]
Publish should export a ballot manifest. The goal of this is to provide a quick way to get a list of the ballots 

The focus on this is to create dictionaries for quickly going through all the ballots. 

This serves two main purposes
1. Retrieval of ballots for loading purposes
2. Verify the tracking information

The expectation is two Ballot Manifest classes which in publish.py would be constructed and would be exported along with the published data at the root level. 

```py
# Both these are temp names for the ticket. 

@dataclass
class BallotInfo:
      tracker_hash: str
      tracker_code: str
      object_id: str
      file: Optional[FileInfo]

@dataclass
class FileInfo
      name: str
      path: str
      Optional[hash]: str
```

**NOTE:** For the `hash`, the [SHA256](https://www.quickprogrammingtips.com/python/how-to-calculate-sha256-hash-of-a-file-in-python.html) is a convenience for identifying the file as recommended by @danwallach . There will be a separate issue to do the SHA256 hash since this is a larger lift. 

The Manifests should exists in two flavors. One for the spoiled or any other `PlaintextBallot`s and one for `CiphertextAcceptedBallot`s. They should each have a function that can take the file info so that Ballot Manifests can be created simply for the Tracking codes at the end of an election. 

The `PlaintextBallotManifest` should look something like this:
```py
class PlaintextBallotManifest:
       ballots: Dict[str, BallotInfo]

       def add_ballot(ballot, file=None)
```
where the identifier is the `object_id`. This may change in time.

```py
class CiphertextAcceptedBallotManifest:
           cast: Dict[str, BallotInfo]
           spoiled: Dict[str, BallotInfo]

          def add_ballot(ballot, file=None)
```

The final steps will be to implement this in `publish.py`. These manifests will be constructed in `publish.py` and then exported into the results folder. For example:

```py
spoiled_ballot_manifest = PlaintextBallotManifest(...)
...
# Add ballot info to this manifest 
...
spoiled_ballot_manifest.to_json_file(ballot_manifest_name, RESULTS_DIR)
```

This can be found by taking a look at [`publish.py`](https://github.com/microsoft/electionguard-python/blob/main/src/electionguard/publish.py)

**Comment by danwallach** [comment]
Also the SHA256 hash of the file.

**Comment by devil-cyber** [comment]
I would like to work on this. It would be great if you could assign this

**Comment by keithrfung** [comment]
I got you. Be sure to ensure the file is using `serializable` like the other files.

**Comment by devil-cyber** [comment]
Ok

**Comment by keithrfung** [comment]
@devil-cyber Sorry for the delayed response, but I got you. I'll add some details on the card itself.

**Comment by keithrfung** [comment]
@devil-cyber I gave a lot more detail. Hopefully this is helpful.

**Comment by keithrfung** [comment]
@danwallach Do you think the SHA256 is mandatory?

If this works in publish, all the files will have to be written out then read back in to do the SHA256 hash.

**Comment by danwallach** [comment]
Here's how arlo-e2e does it:
https://github.com/votingworks/arlo-e2e/blob/main/src/arlo_e2e/manifest.py

You'll see that the manifests have a bunch of other handy features like being able to merge them together as well as being able to write out `index.html` files (which you need if you're using a static web hosting service).
